#!/bin/sh
set -e

CODE=$1

if [ "$CODE" -gt 10 ]; then
    echo "throwing error $CODE to stderr" >&2
    exit $CODE
elif [ "$CODE" -gt 0 ]; then
    echo "throwing error $CODE"
    exit $CODE
else
    echo "everything is OK"
    exit 0
fi
