---
title: "Examples and use-cases"
author: "Rich FitzJohn"
date: "2018-07-02"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using docker with stevedore}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## Using a database in testing

This example requires the `redux` package, which is available on
CRAN and can be installed with

```r
install.packages("redux")
```

```r
docker <- stevedore::docker_client()
```

```
## The option 'stevedore.spec.path' not set - using temporary dir
```

```r
redis <- docker$container$run("redis", name = "redis", ports = "6379",
                              detach = TRUE, rm = TRUE)
```

We now have a redis server running on 32775

```r
redis$ports()
```

```
##   container_port protocol host_ip host_port
## 1           6379      tcp 0.0.0.0     32775
```

Make a connection to the Redis server:

```r
con <- redux::hiredis(port = redis$ports()$host_port)
```

and we can communicate with the Redis server:

```r
con$PING()
```

```
## [Redis: PONG]
```

Because this is a brand new container we can write data without
worrying about clobbering data that already exists:

```r
con$SET("key", "hello redis")
```

```
## [Redis: OK]
```

```r
con$GET("key")
```

```
## [1] "hello redis"
```

And we can get a fresh copy of Redis by simply starting a new copy
of redis

```r
redis$kill()
```

```
## NULL
```

```r
redis <- docker$container$run("redis", name = "redis", ports = "6379",
                              detach = TRUE, rm = TRUE)
con <- redux::hiredis(port = redis$ports()$host_port)
con$KEYS("*")
```

```
## list()
```

```r
redis$kill()
```

```
## NULL
```

The same approach works for other database that might be large or
awkward to install, such as Postgres or MySQL.

## Testing shiny apps

(this section is not actually run because doing anything with it
requires looking in a web browser)

The rocker project has a shiny container that provides an easy to
use version of the shiny server.  If we have a directory `app`
that contains a shiny application we can map this with:

```r
volumes <- sprintf("%s:%s", normalizePath("app"), "/srv/shiny-server/")
```

(see the [shiny docker image
documentation](https://hub.docker.com/r/rocker/shiny) for the
destination path.

We can start this with

```r
shiny <- docker$container$run("rocker/shiny", name = "shiny", ports = "3838",
                              volumes = volumes,
                              detach = TRUE, rm = TRUE)
```

In an interactive session, you can visit the shiny server:

```r
browseURL(sprintf("http://localhost:%s", shiny$ports()$host_port))
```

## Package testing

You can build an image that contains all the bits required to test
your package and then run tests using that image.  This ensures
that you're running in a totally clean environment (and that you
really know what all the dependencies of your package are)


For this we have a dockerfile, which contains
```plain
FROM r-base

RUN apt-get update && \
        apt-get install -yy \
                git \
                libcurl4-openssl-dev \
                libssl-dev \
                qpdf

RUN install2.r --error \
        curl \
        knitr \
        openssl \
        rcmdcheck \
        rmarkdown \
        rcorpora \
        testthat \
        uuid

COPY tester.sh /usr/local/bin
RUN chmod +x /usr/local/bin/tester.sh

ENTRYPOINT ["/usr/local/bin/tester.sh"]
```

And the script `tester.sh` (copied into the docker image above)
which contains:

```r
lang_output(readLines("tester/tester.sh"), "shell")
```

```
## ```shell
## #!/usr/bin/env bash
## set -e
##
## if [[ "$#" -ne 1 ]]; then
##     echo "Expected one argument"
##     exit 1
## fi
## SRC=$1
##
## if echo $SRC | grep -q "^https://"; then
##     DEST=$(mktemp -d)
##     git clone $SRC $DEST
##     SRC=$DEST
## fi
##
## if [ ! -f "$SRC/DESCRIPTION" ]; then
##     echo "Did not find a DESCRIPTION" file
##     exit 1
## fi
##
## PACKAGE=$(grep '^Package:' "$SRC/DESCRIPTION" | \
##                  sed -E 's/^Package:[[:space:]]+//')
## R CMD build $SRC
## PACKAGE_TGZ=$(ls -1tr ${PACKAGE}*gz | tail -n1)
##
## export _R_CHECK_CRAN_INCOMING_=FALSE
## Rscript -e "rcmdcheck::rcmdcheck('$PACKAGE_TGZ', args = c('--as-cran', '--no-manual'))"
## ```
```

```r
img <- docker$image$build("tester", tag = "richfitz/tester")
```

```
## Step 1/6 : FROM r-base
##  ---> 190658892827
## Step 2/6 : RUN apt-get update &&         apt-get install -yy                 git                 libcurl4-openssl-dev                 libssl-dev                 qpdf
##  ---> Running in ec62d2f21f09
## Get:1 http://cdn-fastly.deb.debian.org/debian testing InRelease [150 kB]
## Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages [7,491 kB]
## Get:3 http://cdn-fastly.deb.debian.org/debian sid InRelease [247 kB]
## Get:4 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages [8,060 kB]
## Fetched 15.9 MB in 11s (1,490 kB/s)
## Reading package lists...
## Reading package lists...
## Building dependency tree...
## Reading state information...
## The following additional packages will be installed:
##   git-man libcurl3-gnutls libedit2 liberror-perl libpcre2-8-0 libqpdf21
##   libssl1.0.2 openssh-client
## Suggested packages:
##   git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
##   gitweb git-cvs git-mediawiki git-svn libcurl4-doc libidn11-dev libkrb5-dev
##   libldap2-dev librtmp-dev libssh2-1-dev libssl-doc keychain libpam-ssh
##   monkeysphere ssh-askpass
## The following NEW packages will be installed:
##   git git-man libcurl3-gnutls libcurl4-openssl-dev libedit2 liberror-perl
##   libpcre2-8-0 libqpdf21 libssl-dev libssl1.0.2 openssh-client qpdf
## 0 upgraded, 12 newly installed, 0 to remove and 26 not upgraded.
## Need to get 11.8 MB of archives.
## After this operation, 55.2 MB of additional disk space will be used.
## Get:1 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libedit2 amd64 3.1-20180525-1 [86.8 kB]
## Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libssl1.0.2 amd64 1.0.2o-1 [1,296 kB]
## Get:3 http://cdn-fastly.deb.debian.org/debian testing/main amd64 openssh-client amd64 1:7.7p1-2 [802 kB]
## Get:4 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libcurl3-gnutls amd64 7.60.0-2 [314 kB]
## Get:5 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libpcre2-8-0 amd64 10.31-3 [208 kB]
## Get:6 http://cdn-fastly.deb.debian.org/debian testing/main amd64 liberror-perl all 0.17026-1 [30.9 kB]
## Get:7 http://cdn-fastly.deb.debian.org/debian testing/main amd64 git-man all 1:2.18.0-1 [1,564 kB]
## Get:8 http://cdn-fastly.deb.debian.org/debian testing/main amd64 git amd64 1:2.18.0-1 [4,891 kB]
## Get:9 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libcurl4-openssl-dev amd64 7.60.0-2 [401 kB]
## Get:10 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libqpdf21 amd64 8.1.0-1 [344 kB]
## Get:11 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libssl-dev amd64 1.1.0h-4 [1,590 kB]
## Get:12 http://cdn-fastly.deb.debian.org/debian testing/main amd64 qpdf amd64 8.1.0-1 [285 kB]
## [91mdebconf: delaying package configuration, since apt-utils is not installed
## [0mFetched 11.8 MB in 5s (2,216 kB/s)
## Selecting previously unselected package libedit2:amd64.
## (Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 21345 files and directories currently installed.)
## Preparing to unpack .../00-libedit2_3.1-20180525-1_amd64.deb ...
## Unpacking libedit2:amd64 (3.1-20180525-1) ...
## Selecting previously unselected package libssl1.0.2:amd64.
## Preparing to unpack .../01-libssl1.0.2_1.0.2o-1_amd64.deb ...
## Unpacking libssl1.0.2:amd64 (1.0.2o-1) ...
## Selecting previously unselected package openssh-client.
## Preparing to unpack .../02-openssh-client_1%3a7.7p1-2_amd64.deb ...
## Unpacking openssh-client (1:7.7p1-2) ...
## Selecting previously unselected package libcurl3-gnutls:amd64.
## Preparing to unpack .../03-libcurl3-gnutls_7.60.0-2_amd64.deb ...
## Unpacking libcurl3-gnutls:amd64 (7.60.0-2) ...
## Selecting previously unselected package libpcre2-8-0:amd64.
## Preparing to unpack .../04-libpcre2-8-0_10.31-3_amd64.deb ...
## Unpacking libpcre2-8-0:amd64 (10.31-3) ...
## Selecting previously unselected package liberror-perl.
## Preparing to unpack .../05-liberror-perl_0.17026-1_all.deb ...
## Unpacking liberror-perl (0.17026-1) ...
## Selecting previously unselected package git-man.
## Preparing to unpack .../06-git-man_1%3a2.18.0-1_all.deb ...
## Unpacking git-man (1:2.18.0-1) ...
## Selecting previously unselected package git.
## Preparing to unpack .../07-git_1%3a2.18.0-1_amd64.deb ...
## Unpacking git (1:2.18.0-1) ...
## Selecting previously unselected package libcurl4-openssl-dev:amd64.
## Preparing to unpack .../08-libcurl4-openssl-dev_7.60.0-2_amd64.deb ...
## Unpacking libcurl4-openssl-dev:amd64 (7.60.0-2) ...
## Selecting previously unselected package libqpdf21:amd64.
## Preparing to unpack .../09-libqpdf21_8.1.0-1_amd64.deb ...
## Unpacking libqpdf21:amd64 (8.1.0-1) ...
## Selecting previously unselected package libssl-dev:amd64.
## Preparing to unpack .../10-libssl-dev_1.1.0h-4_amd64.deb ...
## Unpacking libssl-dev:amd64 (1.1.0h-4) ...
## Selecting previously unselected package qpdf.
## Preparing to unpack .../11-qpdf_8.1.0-1_amd64.deb ...
## Unpacking qpdf (8.1.0-1) ...
## Setting up libedit2:amd64 (3.1-20180525-1) ...
## Setting up git-man (1:2.18.0-1) ...
## Setting up liberror-perl (0.17026-1) ...
## Setting up libcurl3-gnutls:amd64 (7.60.0-2) ...
## Setting up libssl-dev:amd64 (1.1.0h-4) ...
## Setting up libqpdf21:amd64 (8.1.0-1) ...
## Setting up libssl1.0.2:amd64 (1.0.2o-1) ...
## debconf: unable to initialize frontend: Dialog
## debconf: (TERM is not set, so the dialog frontend is not usable.)
## debconf: falling back to frontend: Readline
## Processing triggers for libc-bin (2.27-3) ...
## Processing triggers for man-db (2.8.3-2) ...
## Setting up qpdf (8.1.0-1) ...
## Setting up libpcre2-8-0:amd64 (10.31-3) ...
## Setting up openssh-client (1:7.7p1-2) ...
## Setting up libcurl4-openssl-dev:amd64 (7.60.0-2) ...
## Setting up git (1:2.18.0-1) ...
## Processing triggers for libc-bin (2.27-3) ...
## Removing intermediate container ec62d2f21f09
##  ---> 41caf17f2873
## Step 3/6 : RUN install2.r --error         curl         knitr         openssl         rcmdcheck         rmarkdown         rcorpora         testthat         uuid
##  ---> Running in 29bb967bb3a5
## [91mtrying URL 'https://cloud.r-project.org/src/contrib/curl_3.2.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 367047 bytes (358 KB)
## [0m[91m==[0m[91m==[0m[91m==[0m[91m==[0m[91m===[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m==[0m[91m==[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 358 KB
##
## [0m[91m* installing *source* package ‘curl’ ...
## [0m[91m** package ‘curl’ successfully unpacked and MD5 sums checked
## [0mFound pkg-config cflags and libs!
## Using PKG_CFLAGS=-I/usr/include/x86_64-linux-gnu
## Using PKG_LIBS=-lcurl
## [91m** libs
## [0mrm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o utils.o version.o winidn.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c callbacks.c -o callbacks.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c curl.c -o curl.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c download.c -o download.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c escape.c -o escape.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fetch.c -o fetch.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c form.c -o form.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c getdate.c -o getdate.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c handle.c -o handle.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ieproxy.c -o ieproxy.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c interrupt.c -o interrupt.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c multi.c -o multi.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c nslookup.c -o nslookup.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c reflist.c -o reflist.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c split.c -o split.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ssl.c -o ssl.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.c -o utils.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c version.c -o version.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c winidn.c -o winidn.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o utils.o version.o winidn.o -lcurl -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/curl/libs
## [0m[91m** R
## [0m[91m** data
## [0m[91m*** moving datasets to lazyload DB
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (curl)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91malso installing the dependencies ‘mime’, ‘evaluate’, ‘highr’, ‘markdown’, ‘yaml’
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/mime_0.5.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 12634 bytes (12 KB)
## ==================================================[0m[91m
## downloaded 12 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/evaluate_0.10.1.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 22177 bytes (21 KB)
## ===================================[0m[91m===============
## downloaded 21 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/highr_0.7.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 17505 bytes (17 KB)
## [0m[91m==============================================[0m[91m====
## downloaded 17 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/markdown_0.8.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 80583 bytes (78 KB)
## [0m[91m==========[0m[91m==========[0m[91m==========[0m[91m========[0m[91m====[0m[91m===[0m[91m=[0m[91m=[0m[91m==[0m[91m=
## downloaded 78 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/yaml_2.1.19.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 86157 bytes (84 KB)
## [0m[91m=========[0m[91m==========[0m[91m=========[0m[91m=========[0m[91m====[0m[91m=[0m[91m=[0m[91m===[0m[91m=[0m[91m=[0m[91m==[0m[91m
## downloaded 84 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/knitr_1.20.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 650082 bytes (634 KB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 634 KB
##
## [0m[91m* installing *source* package ‘mime’ ...
## [0m[91m** package ‘mime’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rawmatch.c -o rawmatch.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o mime.so rawmatch.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/mime/libs
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (mime)
## [0m[91m* installing *source* package ‘evaluate’ ...
## [0m[91m** package ‘evaluate’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (evaluate)
## [0m[91m* installing *source* package ‘highr’ ...
## [0m[91m** package ‘highr’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (highr)
## [0m[91m* installing *source* package ‘yaml’ ...
## [0m[91m** package ‘yaml’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.c -o api.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dumper.c -o dumper.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c emitter.c -o emitter.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c implicit.c -o implicit.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c loader.c -o loader.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c parser.c -o parser.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c r_emit.c -o r_emit.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c r_ext.c -o r_ext.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c r_parse.c -o r_parse.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c reader.c -o reader.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c scanner.c -o scanner.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c writer.c -o writer.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o yaml.so api.o dumper.o emitter.o implicit.o loader.o parser.o r_emit.o r_ext.o r_parse.o reader.o scanner.o writer.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/yaml/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (yaml)
## [0m[91m* installing *source* package ‘markdown’ ...
## [0m[91m** package ‘markdown’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rbase64.c -o Rbase64.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rinit.c -o Rinit.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rmarkdown.c -o Rmarkdown.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c autolink.c -o autolink.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c buffer.c -o buffer.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c houdini_href_e.c -o houdini_href_e.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c houdini_html_e.c -o houdini_html_e.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c html.c -o html.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c html_smartypants.c -o html_smartypants.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c markdown.c -o markdown.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c stack.c -o stack.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o markdown.so Rbase64.o Rinit.o Rmarkdown.o autolink.o buffer.o houdini_href_e.o houdini_html_e.o html.o html_smartypants.o markdown.o stack.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/markdown/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (markdown)
## [0m[91m* installing *source* package ‘knitr’ ...
## [0m[91m** package ‘knitr’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** demo
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (knitr)
## [0m[91m
## [0m[91mThe downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/openssl_1.0.1.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 1194261 bytes (1.1 MB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 1.1 MB
##
## [0m[91m* installing *source* package ‘openssl’ ...
## [0m[91m** package ‘openssl’ successfully unpacked and MD5 sums checked
## [0mFound pkg-config cflags and libs!
## Using PKG_CFLAGS=
## Using PKG_LIBS=-l:libssl.so.1.1 -l:libcrypto.so.1.1
## [91m** libs
## [0mrm -f aes.o base64.o bignum.o cert.o compatibility.o diffie.o envelope.o error.o hash.o info.o keygen.o keys.o onload.o openssh.o password.o pem.o pkcs12.o pkcs7.o rand.o rsa.o signing.o ssl.o stream.o write.o openssl.so
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c aes.c -o aes.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bignum.c -o bignum.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c cert.c -o cert.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c compatibility.c -o compatibility.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c diffie.c -o diffie.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c envelope.c -o envelope.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c error.c -o error.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hash.c -o hash.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c info.c -o info.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c keygen.c -o keygen.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c keys.c -o keys.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c onload.c -o onload.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c openssh.c -o openssh.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c password.c -o password.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pem.c -o pem.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pkcs12.c -o pkcs12.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pkcs7.c -o pkcs7.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rand.c -o rand.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rsa.c -o rsa.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c signing.c -o signing.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ssl.c -o ssl.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c stream.c -o stream.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c write.c -o write.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o openssl.so aes.o base64.o bignum.o cert.o compatibility.o diffie.o envelope.o error.o hash.o info.o keygen.o keys.o onload.o openssh.o password.o pem.o pkcs12.o pkcs7.o rand.o rsa.o signing.o ssl.o stream.o write.o -l:libssl.so.1.1 -l:libcrypto.so.1.1 -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/openssl/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (openssl)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91malso installing the dependencies ‘cli’, ‘praise’, ‘rlang’, ‘assertthat’, ‘testthat’, ‘processx’, ‘R6’, ‘callr’, ‘clisymbols’, ‘crayon’, ‘digest’, ‘withr’
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/cli_1.0.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 1933874 bytes (1.8 MB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 1.8 MB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/praise_1.0.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 6100 bytes
## ==================================================
## downloaded 6100 bytes
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/rlang_0.2.1.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 325006 bytes (317 KB)
## [0m[91m==[0m[91m===[0m[91m==[0m[91m===[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m====
## downloaded 317 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/assertthat_0.2.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 11612 bytes (11 KB)
## ==================================================
## downloaded 11 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/testthat_2.0.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 217190 bytes (212 KB)
## [0m[91m===[0m[91m====[0m[91m====[0m[91m===[0m[91m==[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m=[0m[91m====[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m
## downloaded 212 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/processx_3.1.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 78448 bytes (76 KB)
## ====[0m[91m===[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m====[0m[91m=[0m[91m==[0m[91m======[0m[91m====[0m[91m=========[0m[91m==[0m[91m=====[0m[91m===[0m[91m=
## downloaded 76 KB
##
## trying URL 'https://cloud.r-project.org/src/contrib/R6_2.2.2.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 322959 bytes (315 KB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m===[0m[91m==[0m[91m===[0m[91m==[0m[91m===[0m[91m==[0m[91m===[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m===[0m[91m
## downloaded 315 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/callr_2.0.4.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 27352 bytes (26 KB)
## ============================[0m[91m======================
## downloaded 26 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/clisymbols_1.2.0.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 9666 bytes
## [0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m==================================
## downloaded 9666 bytes
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/crayon_1.3.4.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 658694 bytes (643 KB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m
## downloaded 643 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/digest_0.6.15.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 122095 bytes (119 KB)
## [0m[91m=[0m[91m=====[0m[91m=[0m[91m=====[0m[91m=[0m[91m=[0m[91m======[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m
## [0m[91mdownloaded 119 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/withr_2.1.2.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 53578 bytes (52 KB)
## [0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m==[0m[91m==[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m==[0m[91m=[0m[91m=[0m[91m======[0m[91m===[0m[91m=====[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m
## [0m[91mdownloaded 52 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/rcmdcheck_1.2.1.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 483527 bytes (472 KB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m==[0m[91m=[0m[91m==[0m[91m==[0m[91m=
## downloaded 472 KB
##
## [0m[91m* installing *source* package ‘praise’ ...
## [0m[91m** package ‘praise’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (praise)
## [0m[91m* installing *source* package ‘rlang’ ...
## [0m[91m** package ‘rlang’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./lib/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c capture.c -o capture.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./lib/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c export.c -o export.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./lib/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c internal.c -o internal.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./lib/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c lib.c -o lib.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o rlang.so capture.o export.o internal.o lib.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/rlang/libs
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m*** copying figures
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (rlang)
## [0m[91m* installing *source* package ‘assertthat’ ...
## [0m[91m** package ‘assertthat’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (assertthat)
## [0m[91m* installing *source* package ‘R6’ ...
## [0m[91m** package ‘R6’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (R6)
## [0m[91m* installing *source* package ‘clisymbols’ ...
## [0m[91m** package ‘clisymbols’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (clisymbols)
## [0m[91m* installing *source* package ‘crayon’ ...
## [0m[91m** package ‘crayon’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (crayon)
## [0m[91m* installing *source* package ‘digest’ ...
## [0m[91m** package ‘digest’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c aes.c -o aes.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c crc32.c -o crc32.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c digest.c -o digest.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c md5.c -o md5.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pmurhash.c -o pmurhash.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c raes.c -o raes.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sha1.c -o sha1.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sha2.c -o sha2.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sha256.c -o sha256.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c xxhash.c -o xxhash.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o digest.so aes.o crc32.o digest.o init.o md5.o pmurhash.o raes.o sha1.o sha2.o sha256.o xxhash.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/digest/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (digest)
## [0m[91m* installing *source* package ‘withr’ ...
## [0m[91m** package ‘withr’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (withr)
## [0m[91m* installing *source* package ‘cli’ ...
## [0m[91m** package ‘cli’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m*** copying figures
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (cli)
## [0m[91m* installing *source* package ‘testthat’ ...
## [0m[91m** package ‘testthat’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c reassign.c -o reassign.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-catch.cpp -o test-catch.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-example.cpp -o test-example.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-runner.cpp -o test-runner.o
## g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o testthat.so init.o reassign.o test-catch.o test-example.o test-runner.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/testthat/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m*** copying figures
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (testthat)
## [0m[91m* installing *source* package ‘processx’ ...
## [0m[91m** package ‘processx’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wall tools/px.c -o tools/px
## gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  supervisor/supervisor.c supervisor/utils.c \
##       -o supervisor/supervisor
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c poll.c -o poll.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c processx-connection.c -o processx-connection.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c processx-vector.c -o processx-vector.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/childlist.c -o unix/childlist.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/connection.c -o unix/connection.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/processx.c -o unix/processx.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/sigchld.c -o unix/sigchld.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/utils.c -o unix/utils.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/named_pipe.c -o unix/named_pipe.o
## g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-connections.cpp -o test-connections.o
## [91mtest-connections.cpp: In function ‘int open_temp_file(char**, size_t, const char*)’:
## test-connections.cpp:111:5: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
##      (void) write(fd, mypattern, pattern_size);
##      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## [0mg++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/testthat/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-runner.cpp -o test-runner.o
## g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o processx.so init.o poll.o processx-connection.o processx-vector.o unix/childlist.o unix/connection.o unix/processx.o unix/sigchld.o unix/utils.o unix/named_pipe.o test-connections.o test-runner.o -L/usr/lib/R/lib -lR
## [91minstalling via 'install.libs.R' to /usr/local/lib/R/site-library/processx
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (processx)
## [0m[91m* installing *source* package ‘callr’ ...
## [0m[91m** package ‘callr’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (callr)
## [0m[91m* installing *source* package ‘rcmdcheck’ ...
## [0m[91m** package ‘rcmdcheck’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (rcmdcheck)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91malso installing the dependencies ‘Rcpp’, ‘backports’, ‘htmltools’, ‘base64enc’, ‘jsonlite’, ‘rprojroot’, ‘tinytex’
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.17.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 3766351 bytes (3.6 MB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 3.6 MB
##
## trying URL 'https://cloud.r-project.org/src/contrib/backports_1.1.2.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 10900 bytes (10 KB)
## [0m[91m=====[0m[91m=[0m[91m=[0m[91m=[0m[91m=========[0m[91m===[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m=========================
## downloaded 10 KB
##
## trying URL 'https://cloud.r-project.org/src/contrib/htmltools_0.3.6.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 45408 bytes (44 KB)
## [0m[91m==================[0m[91m==================[0m[91m===========[0m[91m===
## downloaded 44 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/base64enc_0.1-3.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 7833 bytes
## ==================================================
## downloaded 7833 bytes
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/jsonlite_1.5.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 1096810 bytes (1.0 MB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m=[0m[91m==[0m[91m=[0m[91m=[0m[91m==========
## downloaded 1.0 MB
##
## trying URL 'https://cloud.r-project.org/src/contrib/rprojroot_1.3-2.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 50414 bytes (49 KB)
## ===============[0m[91m================[0m[91m=================[0m[91m==
## downloaded 49 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/tinytex_0.5.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 17316 bytes (16 KB)
## [0m[91m===============================================[0m[91m===
## downloaded 16 KB
##
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/rmarkdown_1.10.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 2447327 bytes (2.3 MB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m
## [0m[91mdownloaded 2.3 MB
##
## [0m[91m* installing *source* package ‘Rcpp’ ...
## [0m[91m** package ‘Rcpp’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mg++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier.cpp -o barrier.o
## g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/Rcpp/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (Rcpp)
## [0m[91m* installing *source* package ‘backports’ ...
## [0m[91m** package ‘backports’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dotsElt.c -o dotsElt.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dotsLength.c -o dotsLength.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o backports.so dotsElt.o dotsLength.o init.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/backports/libs
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (backports)
## [0m[91m* installing *source* package ‘base64enc’ ...
## [0m[91m** package ‘base64enc’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c uriencode.c -o uriencode.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utf8.c -o utf8.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o base64enc.so base64.o uriencode.o utf8.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/base64enc/libs
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (base64enc)
## [0m[91m* installing *source* package ‘jsonlite’ ...
## [0m[91m** package ‘jsonlite’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_array.c -o collapse_array.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_object.c -o collapse_object.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_pretty.c -o collapse_pretty.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c escape_chars.c -o escape_chars.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c integer64_to_na.c -o integer64_to_na.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_datelist.c -o is_datelist.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_recordlist.c -o is_recordlist.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_scalarlist.c -o is_scalarlist.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c modp_numtoa.c -o modp_numtoa.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c null_to_na.c -o null_to_na.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c num_to_char.c -o num_to_char.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c parse.c -o parse.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c prettify.c -o prettify.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c push_parser.c -o push_parser.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c r-base64.c -o r-base64.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c register.c -o register.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c row_collapse.c -o row_collapse.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c transpose_list.c -o transpose_list.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c validate.c -o validate.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl.c -o yajl/yajl.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_alloc.c -o yajl/yajl_alloc.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_buf.c -o yajl/yajl_buf.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_encode.c -o yajl/yajl_encode.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_gen.c -o yajl/yajl_gen.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_lex.c -o yajl/yajl_lex.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_parser.c -o yajl/yajl_parser.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_tree.c -o yajl/yajl_tree.o
## ar rcs libstatyajl.a yajl/yajl.o yajl/yajl_alloc.o yajl/yajl_buf.o yajl/yajl_encode.o yajl/yajl_gen.o yajl/yajl_lex.o yajl/yajl_parser.o yajl/yajl_tree.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o jsonlite.so base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o -L. -lstatyajl -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/jsonlite/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (jsonlite)
## [0m[91m* installing *source* package ‘tinytex’ ...
## [0m[91m** package ‘tinytex’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (tinytex)
## [0m[91m* installing *source* package ‘htmltools’ ...
## [0m[91m** package ‘htmltools’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mg++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c template.cpp -o template.o
## g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o htmltools.so RcppExports.o init.o template.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/htmltools/libs
## [0m[91m** R
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (htmltools)
## [0m[91m* installing *source* package ‘rprojroot’ ...
## [0m[91m** package ‘rprojroot’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (rprojroot)
## [0m[91m* installing *source* package ‘rmarkdown’ ...
## [0m[91m** package ‘rmarkdown’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (rmarkdown)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/rcorpora_1.2.0.tar.gz'
## [0m[91mContent type 'application/x-gzip'[0m[91m length 955433 bytes (933 KB)
## [0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m===[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=[0m[91m=
## downloaded 933 KB
##
## [0m[91m* installing *source* package ‘rcorpora’ ...
## [0m[91m** package ‘rcorpora’ successfully unpacked and MD5 sums checked
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (rcorpora)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/testthat_2.0.0.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 217190 bytes (212 KB)
## [0m[91m===[0m[91m=[0m[91m===[0m[91m====[0m[91m====[0m[91m===[0m[91m==[0m[91m==[0m[91m====[0m[91m===[0m[91m====[0m[91m====[0m[91m====[0m[91m====[0m[91m=====
## downloaded 212 KB
##
## [0m[91m* installing *source* package ‘testthat’ ...
## [0m[91m** package ‘testthat’ successfully unpacked and MD5 sums checked
## [0m[91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c reassign.c -o reassign.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-catch.cpp -o test-catch.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-example.cpp -o test-example.o
## g++  -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-runner.cpp -o test-runner.o
## g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o testthat.so init.o reassign.o test-catch.o test-example.o test-runner.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/testthat/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m*** copying figures
## [0m[91m** building package indices
## [0m[91m** installing vignettes
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (testthat)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0m[91mtrying URL 'https://cloud.r-project.org/src/contrib/uuid_0.1-2.tar.gz'
## [0m[91mContent type 'application/x-gzip' length 46706 bytes (45 KB)
## [0m[91m=================[0m[91m==================[0m[91m===============
## downloaded 45 KB
##
## [0m[91m* installing *source* package ‘uuid’ ...
## [0m[91m** package ‘uuid’ successfully unpacked and MD5 sums checked
## [0mchecking for gcc... gcc -std=gnu99
## checking whether the C compiler works... yes
## checking for C compiler default output file name... a.out
## checking for suffix of executables...
## checking whether we are cross compiling... no
## checking for suffix of object files... o
## checking whether we are using the GNU C compiler... yes
## checking whether gcc -std=gnu99 accepts -g... yes
## checking for gcc -std=gnu99 option to accept ISO C89... none needed
## checking how to run the C preprocessor... gcc -std=gnu99 -E
## checking for grep that handles long lines and -e... /usr/bin/grep
## checking for egrep... /usr/bin/grep -E
## checking for ANSI C header files... yes
## checking for sys/types.h... yes
## checking for sys/stat.h... yes
## checking for stdlib.h... yes
## checking for string.h... yes
## checking for memory.h... yes
## checking for strings.h... yes
## checking for inttypes.h... yes
## checking for stdint.h... yes
## checking for unistd.h... yes
## checking netinet/in.h usability... yes
## checking netinet/in.h presence... yes
## checking for netinet/in.h... yes
## checking for stdlib.h... (cached) yes
## checking sys/file.h usability... yes
## checking sys/file.h presence... yes
## checking for sys/file.h... yes
## checking sys/ioctl.h usability... yes
## checking sys/ioctl.h presence... yes
## checking for sys/ioctl.h... yes
## checking sys/socket.h usability... yes
## checking sys/socket.h presence... yes
## checking for sys/socket.h... yes
## checking sys/sockio.h usability... no
## checking sys/sockio.h presence... no
## checking for sys/sockio.h... no
## checking sys/syscall.h usability... yes
## checking sys/syscall.h presence... yes
## checking for sys/syscall.h... yes
## checking sys/time.h usability... yes
## checking sys/time.h presence... yes
## checking for sys/time.h... yes
## checking sys/un.h usability... yes
## checking sys/un.h presence... yes
## checking for sys/un.h... yes
## checking for unistd.h... (cached) yes
## checking for net/if.h... yes
## checking for net/if_dl.h... no
## checking for jrand48... yes
## checking for flock... yes
## checking for struct sockaddr.sa_len... no
## configure: creating ./config.status
## config.status: creating src/Makevars
## config.status: creating src/config.h
## [91m** libs
## [0mgcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c R.c -o R.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c clear.c -o clear.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c compare.c -o compare.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c copy.c -o copy.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gen_uuid.c -o gen_uuid.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c isnull.c -o isnull.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pack.c -o pack.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c parse.c -o parse.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unpack.c -o unpack.o
## gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unparse.c -o unparse.o
## gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o uuid.so R.o clear.o compare.o copy.o gen_uuid.o isnull.o pack.o parse.o unpack.o unparse.o -L/usr/lib/R/lib -lR
## [91minstalling to /usr/local/lib/R/site-library/uuid/libs
## [0m[91m** R
## [0m[91m** inst
## [0m[91m** byte-compile and prepare package for lazy loading
## [0m[91m** help
## [0m[91m*** installing help indices
## [0m[91m** building package indices
## [0m[91m** testing if installed package can be loaded
## [0m[91m* DONE (uuid)
## [0m[91m
## The downloaded source packages are in
## 	‘/tmp/downloaded_packages’
## [0mRemoving intermediate container 29bb967bb3a5
##  ---> ab4db8e7e710
## Step 4/6 : COPY tester.sh /usr/local/bin
##  ---> fe61ff49046a
## Step 5/6 : RUN chmod +x /usr/local/bin/tester.sh
##  ---> Running in 51b9c2f2a417
## Removing intermediate container 51b9c2f2a417
##  ---> a644777e367f
## Step 6/6 : ENTRYPOINT ["/usr/local/bin/tester.sh"]
##  ---> Running in d89f5cd04deb
## Removing intermediate container d89f5cd04deb
##  ---> 63c523fa6eb6
## Successfully built 63c523fa6eb6
## Successfully tagged richfitz/tester:latest
```

With this image we can then test packages off github:

```r
invisible(docker$container$run(img, "https://github.com/richfitz/ids",
                               rm = TRUE, stream = stdout()))
```

```
## E> Cloning into '/tmp/tmp.AUaKthULNf'...
## O> * checking for file ‘/tmp/tmp.AUaKthULNf/DESCRIPTION’ ... OK
## O> * preparing ‘ids’:
## O> * checking DESCRIPTION meta-information ... OK
## O> * installing the package to build vignettes
## O> * creating vignettes ... OK
## O> * checking for LF line-endings in source and make files and shell scripts
## O> * checking for empty or unneeded directories
## O> * looking to see if a ‘data/datalist’ file should be added
## O> * building ‘ids_1.0.1.tar.gz’
## E>
## O> ────────────────────────────────────────────────────────────────────────────────
## O> ─  using log directory ‘/tmp/RtmphHFYCQ/file3e415a7ed9/ids.Rcheck’
## O> ─  using R version 3.5.0 (2018-04-23)
## O> ─  using platform: x86_64-pc-linux-gnu (64-bit)
## O> ─  using session charset: UTF-8
## O> ─  using options ‘--no-manual --as-cran’
## O> ✔  checking for file ‘ids/DESCRIPTION’
## O> ─  this is package ‘ids’ version ‘1.0.1’
## O> ✔  checking package namespace information
## O> ✔  checking package dependencies
## O> ✔  checking if this is a source package
## O> ✔  checking if there is a namespace
## O> ✔  checking for executable files
## O> ✔  checking for hidden files and directories
## O> ✔  checking for portable file names
## O> ✔  checking for sufficient/correct file permissions
## O> ✔  checking serialization versions
## O> ✔  checking whether package ‘ids’ can be installed
## O> ✔  checking installed package size
## O> ✔  checking package directory
## O> ✔  checking ‘build’ directory
## O> ✔  checking DESCRIPTION meta-information
## O> ✔  checking top-level files
## O> ✔  checking for left-over files
## O> ✔  checking index information
## O> ✔  checking package subdirectories
## O> ✔  checking R files for non-ASCII characters
## O> ✔  checking R files for syntax errors
## O> ✔  checking whether the package can be loaded
## O> ✔  checking whether the package can be loaded with stated dependencies
## O> ✔  checking whether the package can be unloaded cleanly
## O> ✔  checking whether the namespace can be loaded with stated dependencies
## O> ✔  checking whether the namespace can be unloaded cleanly
## O> ✔  checking loading without being on the library search path
## O> ✔  checking dependencies in R code
## O> ✔  checking S3 generic/method consistency
## O> ✔  checking replacement functions
## O> ✔  checking foreign function calls
## O> ✔  checking R code for possible problems
## O> ✔  checking Rd files
## O> ✔  checking Rd metadata
## O> ✔  checking Rd line widths
## O> ✔  checking Rd cross-references
## O> ✔  checking for missing documentation entries
## O> ✔  checking for code/documentation mismatches
## O> ✔  checking Rd \usage sections
## O> ✔  checking Rd contents
## O> ✔  checking for unstated dependencies in examples
## O> ✔  checking R/sysdata.rda
## O> ✔  checking installed files from ‘inst/doc’
## O> ✔  checking files in ‘vignettes’
## O> ✔  checking examples
## O> ✔  checking for unstated dependencies in ‘tests’
## O> ─  checking tests ...  Running ‘testthat.R’
## O>     OK
## O> ✔  checking for unstated dependencies in vignettes
## O> ✔  checking package vignettes in ‘inst/doc’
## O> ✔  checking re-building of vignette outputs
## O>
## O>
## O>
## O> ── 0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```



(I have cheated here and put all of the dependencies of `ids` into
the docker image via the Dockerfile).

The same approach would work by mounting the package source
directory into the container and passing the path (within the
container) to `$run()`.
