<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using docker with stevedore • stevedore</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Using docker with stevedore">
<meta property="og:description" content="stevedore">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">stevedore</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.9.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/stevedore.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/cookbook.html">Cookbook</a>
    </li>
    <li>
      <a href="../articles/examples.html">Examples and use-cases</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/richfitz/stevedore/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="stevedore_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Using docker with stevedore</h1>
                        <h4 class="author">Rich FitzJohn</h4>
            
            <h4 class="date">2020-01-12</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/richfitz/stevedore/blob/master/vignettes/stevedore.Rmd"><code>vignettes/stevedore.Rmd</code></a></small>
      <div class="hidden name"><code>stevedore.Rmd</code></div>

    </div>

    
    
<p><code>stevedore</code> is an R package for interacting with docker from R. With <code>stevedore</code> you can</p>
<ul>
<li>create, run, manage, remove and destroy containers</li>
<li>build, pull, manage and remove images</li>
<li>create, destroy and interact with docker networks</li>
<li>create, destroy and interact with docker volumes</li>
</ul>
<p>Almost everything that can be done with the docker command line client (the main exception being that is not possible to send input to a container as if you were on a terminal).</p>
<p><code>stevedore</code> directly interacts with the docker server over its HTTP API. This gives a more direct access to docker than going via the command line.</p>
<p>This vignette quickly walks through the core features of the package. Because <code>stevedore</code> wraps the docker API directly there are many more arguments that can be used than are covered here. But this covers the core use.</p>
<p>The main function in the package is <code>docker_client</code>; this will construct an object with which we can talk with the docker server. By default this will look at a number of environment variables and try to connect to the correct daemon. See <code><a href="../reference/docker_client.html">?docker_client</a></code> for information on controlling creating the connection.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span> <span class="op">&lt;-</span> <span class="fu">stevedore</span><span class="fu">::</span><span class="fu"><a href="../reference/docker_client.html">docker_client</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>The client object looks a lot like an <a href="https://github.com/r-lib/R6/"><code>R6</code></a> object (though it is implemented differently because the interface here is automatically generated in ways that don’t play nicely with R6). But if you are at all familiar with R6 objects it should seem quite familiar.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span></code></pre></div>
<pre><code>## &lt;docker_client&gt;
##   config: Manage docker swarm configs
##   container: Work with docker containers
##   image: Work with docker images
##   network: Work with docker networks
##   node: Manage docker swarm nodes
##   plugin: Work with docker plugins
##   secret: Manage docker swarm secrets
##   service: Work with docker services
##   swarm: Manage the docker swarm
##   task: Work with docker tasks
##   volume: Work with docker volumes
##   types: Methods for building complex docker types
##   api_version()
##   connection_info()
##   cp(src, dest)
##   df()
##   events(since = NULL, until = NULL, filters = NULL)
##   help(help_type = getOption("help_type"))
##   info()
##   login(username = NULL, password = NULL, email = NULL,
##       serveraddress = NULL)
##   ping()
##   request(verb, path, query = NULL, body = NULL, headers = NULL,
##       stream = NULL)
##   version()</code></pre>
<p>Each function call (e.g., <code>ping</code>) is callable by accessing with <code><a href="https://rdrr.io/r/base/Extract.html">$</a></code>, such as</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="fu">ping</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "OK"
## attr(,"api_version")
## [1] "1.39"
## attr(,"buildkit_version")
## [1] NA
## attr(,"docker_experimental")
## [1] FALSE</code></pre>
<p>In addition there are “collection” objects (e.g., <code>container</code>) that are accessed using <code><a href="https://rdrr.io/r/base/Extract.html">$</a></code>, like a directory structure</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span></code></pre></div>
<pre><code>## &lt;docker_container_collection&gt;
##   create(image, cmd = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL,
##       health_check = NULL, args_escaped = NULL, volumes = NULL,
##       working_dir = NULL, entrypoint = NULL, network_disabled = NULL,
##       mac_address = NULL, on_build = NULL, labels = NULL,
##       stop_signal = NULL, stop_timeout = NULL, shell = NULL,
##       host_config = NULL, network = NULL, name = NULL)
##   get(id)
##   help(help_type = getOption("help_type"))
##   list(all = NULL, limit = NULL, size = NULL, filters = NULL)
##   prune(filters = NULL)
##   remove(id, delete_volumes = NULL, force = NULL, link = NULL)
##   run(image, cmd = NULL, ..., detach = FALSE, rm = FALSE,
##       stream = stdout(), host_config = NULL)</code></pre>
<p>The interface is designed similarly to the command line docker client (and to the Python docker client), where container commands are within the <code>container</code> collection and image commands are within the <code>image</code> collection and so on (the main difference with the command line client is that the container commands are not at the top level, so it is <code>docker$container$run(...)</code> not <code>docker$run(...)</code>).</p>
<p>To run a container, the <code>docker$container$run</code> command follows the semantics of the command line client and will</p>
<ul>
<li>pull a image if it does not exist</li>
<li>create the container</li>
<li>run the container</li>
<li>fetch the logs</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"hello-world"</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt;
## O&gt; Hello from Docker!
## O&gt; This message shows that your installation appears to be working correctly.
## O&gt;
## O&gt; To generate this message, Docker took the following steps:
## O&gt;  1. The Docker client contacted the Docker daemon.
## O&gt;  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
## O&gt;     (amd64)
## O&gt;  3. The Docker daemon created a new container from that image which runs the
## O&gt;     executable that produces the output you are currently reading.
## O&gt;  4. The Docker daemon streamed that output to the Docker client, which sent it
## O&gt;     to your terminal.
## O&gt;
## O&gt; To try something more ambitious, you can run an Ubuntu container with:
## O&gt;  $ docker run -it ubuntu bash
## O&gt;
## O&gt; Share images, automate workflows, and more with a free Docker ID:
## O&gt;  https://hub.docker.com/
## O&gt;
## O&gt; For more examples and ideas, visit:
## O&gt;  https://docs.docker.com/get-started/
## O&gt;</code></pre>
<p>This returns a list with two elements:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">res</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "container" "logs"</code></pre>
<p>The “logs” element is the logs themselves:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span><span class="op">$</span><span class="va">logs</span></code></pre></div>
<pre><code>## O&gt;
## O&gt; Hello from Docker!
## O&gt; This message shows that your installation appears to be working correctly.
## O&gt;
## O&gt; To generate this message, Docker took the following steps:
## O&gt;  1. The Docker client contacted the Docker daemon.
## O&gt;  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
## O&gt;     (amd64)
## O&gt;  3. The Docker daemon created a new container from that image which runs the
## O&gt;     executable that produces the output you are currently reading.
## O&gt;  4. The Docker daemon streamed that output to the Docker client, which sent it
## O&gt;     to your terminal.
## O&gt;
## O&gt; To try something more ambitious, you can run an Ubuntu container with:
## O&gt;  $ docker run -it ubuntu bash
## O&gt;
## O&gt; Share images, automate workflows, and more with a free Docker ID:
## O&gt;  https://hub.docker.com/
## O&gt;
## O&gt; For more examples and ideas, visit:
## O&gt;  https://docs.docker.com/get-started/
## O&gt;</code></pre>
<p>This is a <code>docker_stream</code> object and codes the output stream using the <code>stream</code> attribute (it can otherwise be treated as a character vector).</p>
<p>The “container” element is an object that can be used to interact with a container</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span><span class="op">$</span><span class="va">container</span></code></pre></div>
<pre><code>## &lt;docker_container&gt;
##   commit(repo = NULL, tag = NULL, author = NULL, changes = NULL,
##       comment = NULL, pause = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, exposed_ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL, cmd = NULL,
##       healthcheck = NULL, args_escaped = NULL, image = NULL,
##       volumes = NULL, working_dir = NULL, entrypoint = NULL,
##       network_disabled = NULL, mac_address = NULL, on_build = NULL,
##       labels = NULL, stop_signal = NULL, stop_timeout = NULL,
##       shell = NULL)
##   cp_in(src, dest)
##   cp_out(src, dest)
##   diff()
##   exec(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL, working_dir = NULL, detach = FALSE,
##       stream = stdout())
##   exec_create(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL, working_dir = NULL)
##   export()
##   get_archive(path, dest)
##   help(help_type = getOption("help_type"))
##   id()
##   image()
##   inspect(reload = TRUE)
##   kill(signal = NULL)
##   labels(reload = TRUE)
##   logs(follow = NULL, stdout = TRUE, stderr = TRUE, since = NULL,
##       until = NULL, timestamps = NULL, tail = NULL, stream = stdout())
##   name()
##   path_stat(path)
##   pause()
##   ports(reload = TRUE)
##   put_archive(src, path, no_overwrite_dir_non_dir = NULL)
##   reload()
##   remove(delete_volumes = NULL, force = NULL, link = NULL)
##   rename(name)
##   resize(h = NULL, w = NULL)
##   restart(t = NULL)
##   start(detach_keys = NULL)
##   stats()
##   status(reload = TRUE)
##   stop(t = NULL)
##   top(ps_args = NULL)
##   unpause()
##   update(cpu_shares = NULL, memory = NULL, cgroup_parent = NULL,
##       blkio_weight = NULL, blkio_weight_device = NULL,
##       blkio_device_read_bps = NULL, blkio_device_write_bps = NULL,
##       blkio_device_read_iops = NULL, blkio_device_write_iops = NULL,
##       cpu_period = NULL, cpu_quota = NULL, cpu_realtime_period = NULL,
##       cpu_realtime_runtime = NULL, cpuset_cpus = NULL,
##       cpuset_mems = NULL, devices = NULL, device_cgroup_rules = NULL,
##       disk_quota = NULL, kernel_memory = NULL,
##       memory_reservation = NULL, memory_swap = NULL,
##       memory_swappiness = NULL, nano_cpus = NULL,
##       oom_kill_disable = NULL, init = NULL, pids_limit = NULL,
##       ulimits = NULL, cpu_count = NULL, cpu_percent = NULL,
##       io_maximum_iops = NULL, io_maximum_bandwidth = NULL,
##       restart_policy = NULL)
##   wait(condition = NULL)</code></pre>
<p>For example the function <code>path_stat</code> gets some information about paths on the container:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">path_stat</span><span class="op">(</span><span class="st">"hello"</span><span class="op">)</span></code></pre></div>
<pre><code>## $name
## [1] "hello"
##
## $size
## [1] 1840
##
## $mode
## [1] 509
##
## $mtime
## [1] "2019-01-01T01:27:56Z"
##
## $linkTarget
## [1] ""</code></pre>
<p>The image can also be returned</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span> <span class="op">&lt;-</span> <span class="va">res</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">image</span><span class="op">(</span><span class="op">)</span>
<span class="va">img</span></code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>which is another object with methods that can be invoked to find out about the image, e.g.:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">history</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##                                                                        id
## 1 sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
## 2                                                               &lt;missing&gt;
##      created
## 1 1546306167
## 2 1546306167
##                                                                                           created_by
## 1                                                                  /bin/sh -c #(nop)  CMD ["/hello"]
## 2 /bin/sh -c #(nop) COPY file:f77490f70ce51da25bd21bfc30cb5e1a24b2b65eb37d4af0c327ddc24f0986a6 in /
##           tags size comment
## 1 hello-wo....    0
## 2              1840</code></pre>
<div id="containers" class="section level2">
<h2 class="hasAnchor">
<a href="#containers" class="anchor"></a>Containers</h2>
<p>The <code>$container</code> object includes methods for interacting with containers:</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span></code></pre></div>
<pre><code>## &lt;docker_container_collection&gt;
##   create(image, cmd = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL,
##       health_check = NULL, args_escaped = NULL, volumes = NULL,
##       working_dir = NULL, entrypoint = NULL, network_disabled = NULL,
##       mac_address = NULL, on_build = NULL, labels = NULL,
##       stop_signal = NULL, stop_timeout = NULL, shell = NULL,
##       host_config = NULL, network = NULL, name = NULL)
##   get(id)
##   help(help_type = getOption("help_type"))
##   list(all = NULL, limit = NULL, size = NULL, filters = NULL)
##   prune(filters = NULL)
##   remove(id, delete_volumes = NULL, force = NULL, link = NULL)
##   run(image, cmd = NULL, ..., detach = FALSE, rm = FALSE,
##       stream = stdout(), host_config = NULL)</code></pre>
<p><code>$create</code> creates a new container (similar to <code>docker container create</code> on the command line) but does not start it.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"hello-world"</span>, name <span class="op">=</span> <span class="st">"hello-stevedore"</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## &lt;docker_container&gt;
##   commit(repo = NULL, tag = NULL, author = NULL, changes = NULL,
##       comment = NULL, pause = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, exposed_ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL, cmd = NULL,
##       healthcheck = NULL, args_escaped = NULL, image = NULL,
##       volumes = NULL, working_dir = NULL, entrypoint = NULL,
##       network_disabled = NULL, mac_address = NULL, on_build = NULL,
##       labels = NULL, stop_signal = NULL, stop_timeout = NULL,
##       shell = NULL)
##   cp_in(src, dest)
##   cp_out(src, dest)
##   diff()
##   exec(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL, working_dir = NULL, detach = FALSE,
##       stream = stdout())
##   exec_create(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL, working_dir = NULL)
##   export()
##   get_archive(path, dest)
##   help(help_type = getOption("help_type"))
##   id()
##   image()
##   inspect(reload = TRUE)
##   kill(signal = NULL)
##   labels(reload = TRUE)
##   logs(follow = NULL, stdout = TRUE, stderr = TRUE, since = NULL,
##       until = NULL, timestamps = NULL, tail = NULL, stream = stdout())
##   name()
##   path_stat(path)
##   pause()
##   ports(reload = TRUE)
##   put_archive(src, path, no_overwrite_dir_non_dir = NULL)
##   reload()
##   remove(delete_volumes = NULL, force = NULL, link = NULL)
##   rename(name)
##   resize(h = NULL, w = NULL)
##   restart(t = NULL)
##   start(detach_keys = NULL)
##   stats()
##   status(reload = TRUE)
##   stop(t = NULL)
##   top(ps_args = NULL)
##   unpause()
##   update(cpu_shares = NULL, memory = NULL, cgroup_parent = NULL,
##       blkio_weight = NULL, blkio_weight_device = NULL,
##       blkio_device_read_bps = NULL, blkio_device_write_bps = NULL,
##       blkio_device_read_iops = NULL, blkio_device_write_iops = NULL,
##       cpu_period = NULL, cpu_quota = NULL, cpu_realtime_period = NULL,
##       cpu_realtime_runtime = NULL, cpuset_cpus = NULL,
##       cpuset_mems = NULL, devices = NULL, device_cgroup_rules = NULL,
##       disk_quota = NULL, kernel_memory = NULL,
##       memory_reservation = NULL, memory_swap = NULL,
##       memory_swappiness = NULL, nano_cpus = NULL,
##       oom_kill_disable = NULL, init = NULL, pids_limit = NULL,
##       ulimits = NULL, cpu_count = NULL, cpu_percent = NULL,
##       io_maximum_iops = NULL, io_maximum_bandwidth = NULL,
##       restart_policy = NULL)
##   wait(condition = NULL)</code></pre>
<p><code>$get</code> creates a <code>docker_container</code> object from an container id or name:</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">get</span><span class="op">(</span><span class="st">"hello-stevedore"</span><span class="op">)</span>
<span class="va">x</span><span class="op">$</span><span class="fu">id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "25ba2590b21fac453aec605af5af7f1595d2169e1324254d97f5a08701b59e6c"</code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span><span class="op">$</span><span class="fu">id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "25ba2590b21fac453aec605af5af7f1595d2169e1324254d97f5a08701b59e6c"</code></pre>
<p><code>$list()</code> lists containers (like <code>docker list</code> on the command line) - by default showing only running containers</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">list</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] id               names            image            image_id
##  [5] command          created          ports            size_rw
##  [9] size_root_fs     labels           state            status
## [13] host_config      network_settings mounts           name
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">list</span><span class="op">(</span>all <span class="op">=</span> <span class="cn">TRUE</span>, limit <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>##                                                                 id
## 1 25ba2590b21fac453aec605af5af7f1595d2169e1324254d97f5a08701b59e6c
## 2 e414940048abbea2a66c33fb5191cc881764955ae0b9110ab48ce29cc29ddcce
##          names
## 1 hello-st....
## 2 frosty_b....
##                                                                     image
## 1                                                             hello-world
## 2 sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
##                                                                  image_id
## 1 sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
## 2 sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
##   command    created        ports size_rw size_root_fs labels   state
## 1  /hello 1578823525 characte....      NA           NA        created
## 2  /hello 1578823523 characte....      NA           NA         exited
##                    status host_config network_settings       mounts
## 1                 Created     default     list(bri.... characte....
## 2 Exited (0) 1 second ago     default     list(bri.... characte....
##              name
## 1 hello-stevedore
## 2   frosty_banzai</code></pre>
<p><code>$remove()</code> removes a container by name or id:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="st">"hello-stevedore"</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p><code>$prune()</code> removes non-running containers (i.e., containers that have exited or containers that have been created but not yet started)</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">prune</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $containers_deleted
## [1] "e414940048abbea2a66c33fb5191cc881764955ae0b9110ab48ce29cc29ddcce"
##
## $space_reclaimed
## [1] 0</code></pre>
<div id="working-with-containers" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-containers" class="anchor"></a>Working with containers</h3>
<p>After creating a container object, there are many more methods to use - all apply to the individual container</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"richfitz/iterate"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1000"</span>, <span class="st">"1"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Most are analogues of similarly named <code>docker</code> command line functions.</p>
<p>First, there are some basic query methods - <code>$id()</code>, <code>$name()</code> and <code>$labels()</code></p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "b553018482d2e4119e20c9ccc54fd7a14e6aa7843f630a5266548f31d755211d"</code></pre>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">name</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "angry_snyder"</code></pre>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">labels</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## stevedore_version
##           "0.0.1"</code></pre>
<p>More detailed information (<strong>much</strong> more detailed) can be retrieved with the <code>$inspect()</code> method</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">inspect</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $id
## [1] "b553018482d2e4119e20c9ccc54fd7a14e6aa7843f630a5266548f31d755211d"
##
## $created
## [1] "2020-01-12T10:05:25.3062459Z"
##
## $path
## [1] "/usr/local/bin/iterate"
##
## $args
## [1] "1000" "1"
##
## $state
## $state$status
## [1] "created"
##
## $state$running
## [1] FALSE
##
## $state$paused
## [1] FALSE
##
## $state$restarting
## [1] FALSE
##
## $state$oom_killed
## [1] FALSE
##
## $state$dead
## [1] FALSE
##
## $state$pid
## [1] 0
##
## $state$exit_code
## [1] 0
##
## $state$error
## [1] ""
##
## $state$started_at
## [1] "0001-01-01T00:00:00Z"
##
## $state$finished_at
## [1] "0001-01-01T00:00:00Z"
##
##
## $image
## [1] "sha256:56b0d98ceb5a402ea61c63ab94a8e7f305cde36e3aa8f080a0b7ab1a8a659e7c"
##
## $resolv_conf_path
## [1] ""
##
## $hostname_path
## [1] ""
##
## $hosts_path
## [1] ""
##
## $log_path
## [1] ""
##
## $node
## NULL
##
## $name
## [1] "/angry_snyder"
##
## $restart_count
## [1] 0
##
## $driver
## [1] "overlay2"
##
## $mount_label
## [1] ""
##
## $process_label
## [1] ""
##
## $app_armor_profile
## [1] ""
##
## $exec_ids
## character(0)
##
## $host_config
## $host_config$cpu_shares
## [1] 0
##
## $host_config$memory
## [1] 0
##
## $host_config$cgroup_parent
## [1] ""
##
## $host_config$blkio_weight
## [1] 0
##
## $host_config$blkio_weight_device
## [1] path   weight
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_read_bps
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_write_bps
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_read_iops
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_write_iops
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cpu_period
## [1] 0
##
## $host_config$cpu_quota
## [1] 0
##
## $host_config$cpu_realtime_period
## [1] 0
##
## $host_config$cpu_realtime_runtime
## [1] 0
##
## $host_config$cpuset_cpus
## [1] ""
##
## $host_config$cpuset_mems
## [1] ""
##
## $host_config$devices
## [1] path_on_host       path_in_container  cgroup_permissions
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$device_cgroup_rules
## character(0)
##
## $host_config$disk_quota
## [1] 0
##
## $host_config$kernel_memory
## [1] 0
##
## $host_config$memory_reservation
## [1] 0
##
## $host_config$memory_swap
## [1] 0
##
## $host_config$memory_swappiness
## [1] NA
##
## $host_config$nano_cpus
## [1] NA
##
## $host_config$oom_kill_disable
## [1] FALSE
##
## $host_config$init
## [1] NA
##
## $host_config$pids_limit
## [1] 0
##
## $host_config$ulimits
## [1] name soft hard
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cpu_count
## [1] 0
##
## $host_config$cpu_percent
## [1] 0
##
## $host_config$io_maximum_iops
## [1] 0
##
## $host_config$io_maximum_bandwidth
## [1] 0
##
## $host_config$binds
## character(0)
##
## $host_config$container_idfile
## [1] ""
##
## $host_config$log_config
## $host_config$log_config$type
## [1] "json-file"
##
## $host_config$log_config$config
## character(0)
##
##
## $host_config$network_mode
## [1] "default"
##
## $host_config$port_bindings
## NULL
##
## $host_config$restart_policy
## $host_config$restart_policy$name
## [1] ""
##
## $host_config$restart_policy$maximum_retry_count
## [1] 0
##
##
## $host_config$auto_remove
## [1] FALSE
##
## $host_config$volume_driver
## [1] ""
##
## $host_config$volumes_from
## character(0)
##
## $host_config$mounts
## [1] target         source         type           read_only
## [5] consistency    bind_options   volume_options tmpfs_options
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cap_add
## character(0)
##
## $host_config$cap_drop
## character(0)
##
## $host_config$dns
## character(0)
##
## $host_config$dns_options
## character(0)
##
## $host_config$dns_search
## character(0)
##
## $host_config$extra_hosts
## character(0)
##
## $host_config$group_add
## character(0)
##
## $host_config$ipc_mode
## [1] "shareable"
##
## $host_config$cgroup
## [1] ""
##
## $host_config$links
## character(0)
##
## $host_config$oom_score_adj
## [1] 0
##
## $host_config$pid_mode
## [1] ""
##
## $host_config$privileged
## [1] FALSE
##
## $host_config$publish_all_ports
## [1] FALSE
##
## $host_config$readonly_rootfs
## [1] FALSE
##
## $host_config$security_opt
## character(0)
##
## $host_config$storage_opt
## NULL
##
## $host_config$tmpfs
## NULL
##
## $host_config$uts_mode
## [1] ""
##
## $host_config$userns_mode
## [1] ""
##
## $host_config$shm_size
## [1] 67108864
##
## $host_config$sysctls
## NULL
##
## $host_config$runtime
## [1] NA
##
## $host_config$console_size
## [1] 0 0
##
## $host_config$isolation
## [1] ""
##
## $host_config$masked_paths
##  [1] "/proc/asound"        "/proc/acpi"          "/proc/kcore"
##  [4] "/proc/keys"          "/proc/latency_stats" "/proc/timer_list"
##  [7] "/proc/timer_stats"   "/proc/sched_debug"   "/proc/scsi"
## [10] "/sys/firmware"
##
## $host_config$readonly_paths
## [1] "/proc/bus"           "/proc/fs"            "/proc/irq"
## [4] "/proc/sys"           "/proc/sysrq-trigger"
##
##
## $graph_driver
## $graph_driver$name
## [1] "overlay2"
##
## $graph_driver$data
##                                                                                                                                                                                                                                                                                           lower_dir
## "/var/lib/docker/overlay2/2ac2803a954a813a808e9c1d1f63edf0153ef0dbc109d1c12db372dc2c1104d7-init/diff:/var/lib/docker/overlay2/530d1f73dec177ad03a0ee31ad04d0802bf29925cd2eed2b8e5f49258c6824a3/diff:/var/lib/docker/overlay2/e1a21604d525ede2c5e9e6d59ac7dceb33bc7469ad98cc9997477a38c310305c/diff"
##                                                                                                                                                                                                                                                                                          merged_dir
##                                                                                                                                                                                                  "/var/lib/docker/overlay2/2ac2803a954a813a808e9c1d1f63edf0153ef0dbc109d1c12db372dc2c1104d7/merged"
##                                                                                                                                                                                                                                                                                           upper_dir
##                                                                                                                                                                                                    "/var/lib/docker/overlay2/2ac2803a954a813a808e9c1d1f63edf0153ef0dbc109d1c12db372dc2c1104d7/diff"
##                                                                                                                                                                                                                                                                                            work_dir
##                                                                                                                                                                                                    "/var/lib/docker/overlay2/2ac2803a954a813a808e9c1d1f63edf0153ef0dbc109d1c12db372dc2c1104d7/work"
##
##
## $size_rw
## [1] NA
##
## $size_root_fs
## [1] NA
##
## $mounts
## [1] type        name        source      destination driver      mode
## [7] rw          propagation
## &lt;0 rows&gt; (or 0-length row.names)
##
## $config
## $config$hostname
## [1] "b553018482d2"
##
## $config$domainname
## [1] ""
##
## $config$user
## [1] ""
##
## $config$attach_stdin
## [1] FALSE
##
## $config$attach_stdout
## [1] FALSE
##
## $config$attach_stderr
## [1] FALSE
##
## $config$exposed_ports
## NULL
##
## $config$tty
## [1] FALSE
##
## $config$open_stdin
## [1] FALSE
##
## $config$stdin_once
## [1] FALSE
##
## $config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $config$cmd
## [1] "1000" "1"
##
## $config$healthcheck
## NULL
##
## $config$args_escaped
## [1] NA
##
## $config$image
## [1] "richfitz/iterate"
##
## $config$volumes
## NULL
##
## $config$working_dir
## [1] ""
##
## $config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $config$network_disabled
## [1] NA
##
## $config$mac_address
## [1] NA
##
## $config$on_build
## character(0)
##
## $config$labels
## stevedore_version
##           "0.0.1"
##
## $config$stop_signal
## [1] NA
##
## $config$stop_timeout
## [1] NA
##
## $config$shell
## character(0)
##
##
## $network_settings
## $network_settings$bridge
## [1] ""
##
## $network_settings$sandbox_id
## [1] ""
##
## $network_settings$hairpin_mode
## [1] FALSE
##
## $network_settings$link_local_ipv6_address
## [1] ""
##
## $network_settings$link_local_ipv6_prefix_len
## [1] 0
##
## $network_settings$ports
## list()
##
## $network_settings$sandbox_key
## [1] ""
##
## $network_settings$secondary_ipaddresses
## [1] addr       prefix_len
## &lt;0 rows&gt; (or 0-length row.names)
##
## $network_settings$secondary_ipv6_addresses
## [1] addr       prefix_len
## &lt;0 rows&gt; (or 0-length row.names)
##
## $network_settings$endpoint_id
## [1] ""
##
## $network_settings$gateway
## [1] ""
##
## $network_settings$global_ipv6_address
## [1] ""
##
## $network_settings$global_ipv6_prefix_len
## [1] 0
##
## $network_settings$ip_address
## [1] ""
##
## $network_settings$ip_prefix_len
## [1] 0
##
## $network_settings$ipv6_gateway
## [1] ""
##
## $network_settings$mac_address
## [1] ""
##
## $network_settings$networks
## $network_settings$networks$bridge
## $network_settings$networks$bridge$ipam_config
## NULL
##
## $network_settings$networks$bridge$links
## character(0)
##
## $network_settings$networks$bridge$aliases
## character(0)
##
## $network_settings$networks$bridge$network_id
## [1] ""
##
## $network_settings$networks$bridge$endpoint_id
## [1] ""
##
## $network_settings$networks$bridge$gateway
## [1] ""
##
## $network_settings$networks$bridge$ip_address
## [1] ""
##
## $network_settings$networks$bridge$ip_prefix_len
## [1] 0
##
## $network_settings$networks$bridge$ipv6_gateway
## [1] ""
##
## $network_settings$networks$bridge$global_ipv6_address
## [1] ""
##
## $network_settings$networks$bridge$global_ipv6_prefix_len
## [1] 0
##
## $network_settings$networks$bridge$mac_address
## [1] ""
##
## $network_settings$networks$bridge$driver_opts
## NULL</code></pre>
<p>The image used by a container can be retrieved with the <code>$image()</code> method</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">image</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>(see below for working with images).</p>
<p>The status of the container (<code>created</code>, <code>running</code>, <code>exited</code>, <code>paused</code>, etc) can be read with <code>$status()</code></p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "created"</code></pre>
<p>The container created by by <code>$create</code> is not running - the <code>$start()</code> method will start it:</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">start</span><span class="op">(</span><span class="op">)</span>
<span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Once the container is running we can query to see what processes are running in it with <code>$top</code> (standing for Table Of Processes)</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">top</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##    PID USER TIME                                         COMMAND
## 1 2918 root 0:00 {iterate} /bin/sh /usr/local/bin/iterate 1000 1
## 2 2953 root 0:00                                         sleep 1</code></pre>
<p>We can also get the logs:</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">logs</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; Doing 1000 iterations with interval 1
## O&gt; Iteration 1...</code></pre>
<p>This returns a special object type <code>docker_stream</code> which allows control over formatting with <code><a href="https://rdrr.io/r/base/format.html">format()</a></code> - the <code>style</code> argument controls how stderr and stdout are printed. There is a <code>stream</code> attribute that can be used to separate out lines too. If a tty was allocated with <code>tty = TRUE</code> the output will be a plain character vector</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/format.html">format</a></span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="fu">logs</span><span class="op">(</span><span class="op">)</span>, style <span class="op">=</span> <span class="st">"plain"</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "Doing 1000 iterations with interval 1\n"
## [2] "Iteration 1...\n"</code></pre>
<p>It can generally be treated as a character vector:</p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">logs</span><span class="op">(</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span></code></pre></div>
<pre><code>## [1] "Doing 1000 iterations with interval 1\n"
## [2] "Iteration 1...\n"</code></pre>
<p>The <code>$logs()</code> method can be used to do a blocking wait on a container. Pass <code>follow = TRUE</code> to follow the logs. You will want to provide a <code>stream</code> argument too, which is where to stream the log to. This can be <code><a href="https://rdrr.io/r/base/showConnections.html">stdout()</a></code> or <code><a href="https://rdrr.io/r/base/showConnections.html">stderr()</a></code>, a file or an R connection.</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"richfitz/iterate"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"10"</span>, <span class="st">"0.1"</span><span class="op">)</span><span class="op">)</span>
<span class="va">y</span><span class="op">$</span><span class="fu">start</span><span class="op">(</span><span class="op">)</span>
<span class="va">y</span><span class="op">$</span><span class="fu">logs</span><span class="op">(</span>stream <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/showConnections.html">stdout</a></span><span class="op">(</span><span class="op">)</span>, follow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; Doing 10 iterations with interval 0.1
## O&gt; Iteration 1...
## O&gt; Iteration 2...
## O&gt; Iteration 3...
## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Iteration 6...
## O&gt; Iteration 7...
## O&gt; Iteration 8...
## O&gt; Iteration 9...
## O&gt; Iteration 10...
## O&gt; Done!</code></pre>
<p>If running this interactively, the logs will print one line at a time - once control returns to R the container has exited. You can escape this streaming using whatever method you use to interrupt an R calculation (depends on which GUI/IDE you are using) but the container will continue regardless - we are just <em>observing</em> a running container.</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "exited"</code></pre>
<p>The other way of blocking until a container has finished is with <code>$wait()</code> which blocks until the container exits, then returns the exit code.</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span><span class="op">$</span><span class="fu">start</span><span class="op">(</span><span class="op">)</span>
<span class="va">y</span><span class="op">$</span><span class="fu">wait</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $exit_code
## [1] 0</code></pre>
<p>Calling <code>$wait()</code> on an exited container is fine, and will just return immediately:</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span><span class="op">$</span><span class="fu">wait</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $exit_code
## [1] 0</code></pre>
<p>Containers can be paused with <code>$pause()</code></p>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">pause</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "paused"</code></pre>
<p>Once paused, they can be restarted with <code>$unpause()</code></p>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">unpause</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Additionally, containers can be <em>restarted</em> with <code>$restart()</code></p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">restart</span><span class="op">(</span>t <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">logs</span><span class="op">(</span>tail <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Iteration 6...
## O&gt; Doing 1000 iterations with interval 1
## O&gt; Iteration 1...</code></pre>
<p>Containers can be stopped with <code>$stop()</code> and removed with <code>$remove()</code> (calling <code>$remove(force = TRUE)</code> will kill the container before removing.</p>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="kw">stop</span><span class="op">(</span>t <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb83"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Once a container has been removed most methods will not work properly:</p>
<div class="sourceCode" id="cb85"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Error: No such container: b553018482d2e4119e20c9ccc54fd7a14e6aa7843f630a5266548f31d755211d</code></pre>
<p>Information about ports (for containers that expose them) can be retrieved with <code>$ports()</code>. The <code>nginx</code> image creates a web server/proxy that exposes port 80 from the container. We can map that to a random port by asking docker to expose port 80 but not saying what to map it to:</p>
<div class="sourceCode" id="cb87"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nginx</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"nginx"</span>, ports <span class="op">=</span> <span class="fl">80</span>,
                              detach <span class="op">=</span> <span class="cn">TRUE</span>, rm <span class="op">=</span> <span class="cn">TRUE</span>,
                              name <span class="op">=</span> <span class="st">"stevedore-nginx"</span><span class="op">)</span>
<span class="va">nginx</span><span class="op">$</span><span class="fu">ports</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   container_port protocol host_ip host_port
## 1             80      tcp 0.0.0.0     32768</code></pre>
<p>(alternatively, use <code>ports = TRUE</code> to act like <code>docker run</code>’s <code>-P</code> and "publish all ports to random ports).</p>
<p>This shows that the port exposed by the the container (80) is mapped to the port 32768 on the host. We can use this to communicate with the server:</p>
<div class="sourceCode" id="cb89"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">url</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"http://localhost:%s"</span>, <span class="va">nginx</span><span class="op">$</span><span class="fu">ports</span><span class="op">(</span><span class="op">)</span><span class="op">$</span><span class="va">host_port</span><span class="op">)</span>
<span class="fu">curl</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/curl/man/parse_headers.html">parse_headers</a></span><span class="op">(</span><span class="fu">curl</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/curl/man/curl_fetch.html">curl_fetch_memory</a></span><span class="op">(</span><span class="va">url</span><span class="op">)</span><span class="op">$</span><span class="va">headers</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "HTTP/1.1 200 OK"
## [2] "Server: nginx/1.17.7"
## [3] "Date: Sun, 12 Jan 2020 10:05:34 GMT"
## [4] "Content-Type: text/html"
## [5] "Content-Length: 612"
## [6] "Last-Modified: Tue, 24 Dec 2019 13:07:53 GMT"
## [7] "Connection: keep-alive"
## [8] "ETag: \"5e020da9-264\""
## [9] "Accept-Ranges: bytes"</code></pre>
<div class="sourceCode" id="cb91"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nginx</span><span class="op">$</span><span class="kw">stop</span><span class="op">(</span>t <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
</div>
</div>
<div id="run-commands-in-running-containers-with-exec" class="section level2">
<h2 class="hasAnchor">
<a href="#run-commands-in-running-containers-with-exec" class="anchor"></a>Run commands in running containers with <code>exec</code>
</h2>
<p>With the command-line tool, <code>docker exec &lt;container name&gt; &lt;command&gt;</code> lets you run an arbitrary command within a running container. <code>stevedore</code> does this with the <code>exec</code> method of a container object.</p>
<p>Reasons for doing this include debugging (using arbitrary commands to inspect/interact with a container while it does its primary task) but it can also be used in deployment (e.g., sending a “go” signal after copying files into the container).</p>
<p>To demonstrate, we need a long running container:</p>
<div class="sourceCode" id="cb93"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"richfitz/iterate"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1000"</span>, <span class="st">"10"</span><span class="op">)</span>,
                          detach <span class="op">=</span> <span class="cn">TRUE</span>, rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">x</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>With the container running we can run additional commands:</p>
<div class="sourceCode" id="cb95"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span> <span class="op">&lt;-</span> <span class="va">x</span><span class="op">$</span><span class="fu">exec</span><span class="op">(</span><span class="st">"ls"</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; bin
## O&gt; dev
## O&gt; etc
## O&gt; home
## O&gt; lib
## O&gt; media
## O&gt; mnt
## O&gt; opt
## O&gt; proc
## O&gt; root
## O&gt; run
## O&gt; sbin
## O&gt; srv
## O&gt; sys
## O&gt; tmp
## O&gt; usr
## O&gt; var</code></pre>
<p>This streams the output of the command by default (to the connection indicated by the <code>stream</code>) argument. Output is also returned as part of the object:</p>
<div class="sourceCode" id="cb97"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span></code></pre></div>
<pre><code>## $id
## [1] "62e5e653b88bda606b07b286bd27ca8d0b653e3000e76004463b609974722d0e"
##
## $exit_code
## [1] 0
##
## $details
## $details$can_remove
## [1] FALSE
##
## $details$detach_keys
## [1] ""
##
## $details$id
## [1] "62e5e653b88bda606b07b286bd27ca8d0b653e3000e76004463b609974722d0e"
##
## $details$running
## [1] FALSE
##
## $details$exit_code
## [1] 0
##
## $details$process_config
## $details$process_config$privileged
## [1] FALSE
##
## $details$process_config$user
## [1] NA
##
## $details$process_config$tty
## [1] FALSE
##
## $details$process_config$entrypoint
## [1] "ls"
##
## $details$process_config$arguments
## character(0)
##
##
## $details$open_stdin
## [1] FALSE
##
## $details$open_stderr
## [1] TRUE
##
## $details$open_stdout
## [1] TRUE
##
## $details$container_id
## [1] "9317cd764a3c2648de3d284ea084466afc1512fba48625233498ee1dc9754da2"
##
## $details$pid
## [1] 3673
##
##
## $output
## O&gt; bin
## O&gt; dev
## O&gt; etc
## O&gt; home
## O&gt; lib
## O&gt; media
## O&gt; mnt
## O&gt; opt
## O&gt; proc
## O&gt; root
## O&gt; run
## O&gt; sbin
## O&gt; srv
## O&gt; sys
## O&gt; tmp
## O&gt; usr
## O&gt; var</code></pre>
</div>
<div id="copy-files-into-and-out-of-containers" class="section level2">
<h2 class="hasAnchor">
<a href="#copy-files-into-and-out-of-containers" class="anchor"></a>Copy files into and out of containers</h2>
<p>Just like <code>docker cp</code>, <code>stevedore</code> lets you copy files into and out of containers. The logic mimics the logic in the docker command line client as closely as possible.</p>
<p>To copy a file into our container <code>x</code>, use <code>$cp_in</code></p>
<div class="sourceCode" id="cb99"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">path</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempfile</a></span><span class="op">(</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="st">"hello"</span>, <span class="va">path</span><span class="op">)</span>
<span class="va">x</span><span class="op">$</span><span class="fu">cp_in</span><span class="op">(</span><span class="va">path</span>, <span class="st">"/hello"</span><span class="op">)</span></code></pre></div>
<p>And the new file is on the container</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">exec</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"cat"</span>, <span class="st">"/hello"</span><span class="op">)</span>, stream <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">$</span><span class="va">output</span></code></pre></div>
<pre><code>## O&gt; hello</code></pre>
<p>The input can be a single file or a single directory.</p>
<p>To copy out, use <code>$cp_out</code></p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempfile</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">x</span><span class="op">$</span><span class="fu">cp_out</span><span class="op">(</span><span class="st">"/usr/local/bin/iterate"</span>, <span class="va">dest</span><span class="op">)</span></code></pre></div>
<p>Here is the iterate script, from the container:</p>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/readLines.html">readLines</a></span><span class="op">(</span><span class="va">dest</span>, n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## #!/bin/sh
## set -e
##
## if [ "$#" -ge 1 ]; then
##     TIMES=$1
## else
##     TIMES=10
## fi
##
## if [ "$#" -ge 2 ]; then</code></pre>
<p>There is also a convenience method at the root of the docker object that behaves more like <code>docker cp</code> and requires that one of the source or destination arguments is given in <code>&lt;container&gt;:&lt;path&gt;</code> format:</p>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">src</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="fu">name</span><span class="op">(</span><span class="op">)</span>, <span class="st">":/usr/local/bin/iterate"</span><span class="op">)</span>
<span class="va">src</span></code></pre></div>
<pre><code>## [1] "sad_ptolemy:/usr/local/bin/iterate"</code></pre>
<p>as</p>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dest2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempfile</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">docker</span><span class="op">$</span><span class="fu">cp</span><span class="op">(</span><span class="va">src</span>, <span class="va">dest2</span><span class="op">)</span></code></pre></div>
<p>which achieves the same thing as the <code>$cp_out</code> command above.</p>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="fu">tools</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/tools/md5sum.html">md5sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">dest</span>, <span class="va">dest2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "87bea4544cfd716dbab5030deb873b62" "87bea4544cfd716dbab5030deb873b62"</code></pre>
<p>(don’t forget to remove your detached containers later!)</p>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span><span class="op">$</span><span class="fu">kill</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
</div>
<div id="images" class="section level2">
<h2 class="hasAnchor">
<a href="#images" class="anchor"></a>Images</h2>
<div id="pulling" class="section level3">
<h3 class="hasAnchor">
<a href="#pulling" class="anchor"></a>Pulling</h3>
<p>Images can be directly pulled with <code>docker$image$pull</code> providing an image name (as either <code>&lt;repo&gt;</code> or <code>&lt;repo&gt;:&lt;tag&gt;</code>. If the image exists already this will be quick, and if the network connection is down then this will fail.</p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">image</span><span class="op">$</span><span class="fu">pull</span><span class="op">(</span><span class="st">"bash:latest"</span><span class="op">)</span></code></pre></div>
<pre><code>## Pulling from library/bash latest
## Already exists 89d9c30c1d48
## Pulling fs layer 1cd014c0f09d
## Pulling fs layer fed606654955
## 1cd014c0f09d: Downloading 31.87 kB/3.17 MB 1%
## fed606654955: Downloading 340 B/340 B 100%
## Verifying Checksum fed606654955
## Download complete fed606654955
## 1cd014c0f09d: Downloading 228.48 kB/3.17 MB 7%
## 1cd014c0f09d: Downloading 588.92 kB/3.17 MB 19%
## 1cd014c0f09d: Downloading 1.08 MB/3.17 MB 34%
## 1cd014c0f09d: Downloading 1.41 MB/3.17 MB 44%
## 1cd014c0f09d: Downloading 1.75 MB/3.17 MB 55%
## 1cd014c0f09d: Downloading 2.08 MB/3.17 MB 65%
## 1cd014c0f09d: Downloading 2.42 MB/3.17 MB 76%
## 1cd014c0f09d: Downloading 2.75 MB/3.17 MB 87%
## 1cd014c0f09d: Downloading 3.07 MB/3.17 MB 97%
## Verifying Checksum 1cd014c0f09d
## Download complete 1cd014c0f09d
## 1cd014c0f09d: Extracting 32.77 kB/3.17 MB 1%
## 1cd014c0f09d: Extracting 262.14 kB/3.17 MB 8%
## 1cd014c0f09d: Extracting 2.16 MB/3.17 MB 68%
## 1cd014c0f09d: Extracting 2.98 MB/3.17 MB 94%
## 1cd014c0f09d: Extracting 3.05 MB/3.17 MB 96%
## 1cd014c0f09d: Extracting 3.15 MB/3.17 MB 99%
## 1cd014c0f09d: Extracting 3.17 MB/3.17 MB 100%
## Pull complete 1cd014c0f09d
## fed606654955: Extracting 340 B/340 B 100%
## fed606654955: Extracting 340 B/340 B 100%
## Pull complete fed606654955
## Digest: sha256:293ac2e5c5be7722d6f4aa620c6451aea359eec1f2f6d5c0faef948b86e449cd
## Status: Downloaded newer image for bash:latest</code></pre>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
</div>
<div id="the-object-returned-by-pull-is-an-image-object---that-can-be" class="section level3">
<h3 class="hasAnchor">
<a href="#the-object-returned-by-pull-is-an-image-object---that-can-be" class="anchor"></a>The object returned by pull is an image object - that can be</h3>
</div>
<div id="created-by-using-get" class="section level3">
<h3 class="hasAnchor">
<a href="#created-by-using-get" class="anchor"></a>created by using <code>$get</code>
</h3>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">image</span><span class="op">$</span><span class="fu">get</span><span class="op">(</span><span class="st">"bash:latest"</span><span class="op">)</span></code></pre></div>
</div>
<div id="building" class="section level3">
<h3 class="hasAnchor">
<a href="#building" class="anchor"></a>Building</h3>
<p>The other common way of getting images is to build them (the equivalent of <code>docker build</code>). So if we have a path (here, <code>iterate</code>) containing a Dockerfile:</p>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/list.files.html">dir</a></span><span class="op">(</span><span class="st">"iterate"</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "Dockerfile" "iterate"</code></pre>
<p>The Dockerfile itself contains:</p>
<pre class="plain"><code>FROM alpine:latest
COPY iterate /usr/local/bin/iterate
CMD chmod +x /usr/local/bin/iterate
LABEL stevedore_version 0.0.1
ENTRYPOINT ["/usr/local/bin/iterate"]</code></pre>
<p>and the <code>iterate</code> file is an executable shell script containing:</p>
<pre class="shell"><code>#!/bin/sh
set -e

if [ "$#" -ge 1 ]; then
    TIMES=$1
else
    TIMES=10
fi

if [ "$#" -ge 2 ]; then
    INTERVAL=$2
else
    INTERVAL=1
fi

echo "Doing $TIMES iterations with interval $INTERVAL"
i=0
while [ $i -lt $TIMES ]; do
    let i+=1
    echo "Iteration $i..."
    sleep $INTERVAL
done
echo "Done!"</code></pre>
<p>We can build this image using:</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">image</span><span class="op">$</span><span class="fu">build</span><span class="op">(</span><span class="st">"iterate"</span>, tag <span class="op">=</span> <span class="st">"richfitz/iterate"</span>, nocache <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Step 1/5 : FROM alpine:latest
##  ---&gt; cc0abc535e36
## Step 2/5 : COPY iterate /usr/local/bin/iterate
##  ---&gt; bfead14674a0
## Step 3/5 : CMD chmod +x /usr/local/bin/iterate
##  ---&gt; Running in 3ffd8d1225b8
## Removing intermediate container 3ffd8d1225b8
##  ---&gt; d5b6a0eaa685
## Step 4/5 : LABEL stevedore_version 0.0.1
##  ---&gt; Running in c150ea2a1f95
## Removing intermediate container c150ea2a1f95
##  ---&gt; 346745e9ebc8
## Step 5/5 : ENTRYPOINT ["/usr/local/bin/iterate"]
##  ---&gt; Running in a17b554ff885
## Removing intermediate container a17b554ff885
##  ---&gt; 244154bfbb99
## Successfully built 244154bfbb99
## Successfully tagged richfitz/iterate:latest</code></pre>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span></code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>The newly created image is returned as an image object and can be used via <code>$container$run()</code></p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/invisible.html">invisible</a></span><span class="op">(</span>
  <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="va">img</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"10"</span>, <span class="st">"0.1"</span><span class="op">)</span>, rm <span class="op">=</span> <span class="cn">TRUE</span>, stream <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/showConnections.html">stdout</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; Doing 10 iterations with interval 0.1
## O&gt; Iteration 1...
## O&gt; Iteration 2...
## O&gt; Iteration 3...
## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Iteration 6...
## O&gt; Iteration 7...
## O&gt; Iteration 8...
## O&gt; Iteration 9...
## O&gt; Iteration 10...
## O&gt; Done!</code></pre>
</div>
<div id="importing" class="section level3">
<h3 class="hasAnchor">
<a href="#importing" class="anchor"></a>Importing</h3>
<p>There is a third way of creating an image, which is to import it from a tar archive. This is not yet documented (<strong>TODO</strong>) but can be done via <code>$image$import()</code></p>
</div>
<div id="working-with-image-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-image-objects" class="anchor"></a>Working with image objects</h3>
<p>Each image object has a number of methods.</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">image</span><span class="op">$</span><span class="fu">get</span><span class="op">(</span><span class="st">"richfitz/iterate"</span><span class="op">)</span>
<span class="va">img</span></code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>The <code>$id()</code>, <code>$short_id()</code>, <code>$labels()</code>, <code>$name()</code> and <code>$tags()</code> query basic information about an image</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "sha256:244154bfbb9995fc3c5fede726ec4c2679ba393375f2a8130ffd8537dcce3285"</code></pre>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">short_id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "sha256:244154bfbb"</code></pre>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">labels</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## stevedore_version
##           "0.0.1"</code></pre>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">name</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "richfitz/iterate"</code></pre>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">tags</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "richfitz/iterate:latest"</code></pre>
<p>(short_id<code>is always 10 characters long and does not include a leading</code>sha256:`).</p>
<p>The <code>inspect()</code> method returns detailed information about the image</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">inspect</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $id
## [1] "sha256:244154bfbb9995fc3c5fede726ec4c2679ba393375f2a8130ffd8537dcce3285"
##
## $repo_tags
## [1] "richfitz/iterate:latest"
##
## $repo_digests
## character(0)
##
## $parent
## [1] "sha256:346745e9ebc8af6b623cdf5729ceddfd215e33d7886a7e72e71beba46d9bceca"
##
## $comment
## [1] ""
##
## $created
## [1] "2020-01-12T10:05:44.4499183Z"
##
## $container
## [1] "a17b554ff885999f2bd26d6716e358fea4d3e01194986dca3c0e6c4b57c095db"
##
## $container_config
## $container_config$hostname
## [1] "a17b554ff885"
##
## $container_config$domainname
## [1] ""
##
## $container_config$user
## [1] ""
##
## $container_config$attach_stdin
## [1] FALSE
##
## $container_config$attach_stdout
## [1] FALSE
##
## $container_config$attach_stderr
## [1] FALSE
##
## $container_config$exposed_ports
## NULL
##
## $container_config$tty
## [1] FALSE
##
## $container_config$open_stdin
## [1] FALSE
##
## $container_config$stdin_once
## [1] FALSE
##
## $container_config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $container_config$cmd
## [1] "/bin/sh"
## [2] "-c"
## [3] "#(nop) "
## [4] "ENTRYPOINT [\"/usr/local/bin/iterate\"]"
##
## $container_config$healthcheck
## NULL
##
## $container_config$args_escaped
## [1] TRUE
##
## $container_config$image
## [1] "sha256:346745e9ebc8af6b623cdf5729ceddfd215e33d7886a7e72e71beba46d9bceca"
##
## $container_config$volumes
## NULL
##
## $container_config$working_dir
## [1] ""
##
## $container_config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $container_config$network_disabled
## [1] NA
##
## $container_config$mac_address
## [1] NA
##
## $container_config$on_build
## character(0)
##
## $container_config$labels
## stevedore_version
##           "0.0.1"
##
## $container_config$stop_signal
## [1] NA
##
## $container_config$stop_timeout
## [1] NA
##
## $container_config$shell
## character(0)
##
##
## $docker_version
## [1] "18.09.2"
##
## $author
## [1] ""
##
## $config
## $config$hostname
## [1] ""
##
## $config$domainname
## [1] ""
##
## $config$user
## [1] ""
##
## $config$attach_stdin
## [1] FALSE
##
## $config$attach_stdout
## [1] FALSE
##
## $config$attach_stderr
## [1] FALSE
##
## $config$exposed_ports
## NULL
##
## $config$tty
## [1] FALSE
##
## $config$open_stdin
## [1] FALSE
##
## $config$stdin_once
## [1] FALSE
##
## $config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $config$cmd
## [1] "/bin/sh"                         "-c"
## [3] "chmod +x /usr/local/bin/iterate"
##
## $config$healthcheck
## NULL
##
## $config$args_escaped
## [1] TRUE
##
## $config$image
## [1] "sha256:346745e9ebc8af6b623cdf5729ceddfd215e33d7886a7e72e71beba46d9bceca"
##
## $config$volumes
## NULL
##
## $config$working_dir
## [1] ""
##
## $config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $config$network_disabled
## [1] NA
##
## $config$mac_address
## [1] NA
##
## $config$on_build
## character(0)
##
## $config$labels
## stevedore_version
##           "0.0.1"
##
## $config$stop_signal
## [1] NA
##
## $config$stop_timeout
## [1] NA
##
## $config$shell
## character(0)
##
##
## $architecture
## [1] "amd64"
##
## $os
## [1] "linux"
##
## $os_version
## [1] NA
##
## $size
## [1] 5591606
##
## $virtual_size
## [1] 5591606
##
## $graph_driver
## $graph_driver$name
## [1] "overlay2"
##
## $graph_driver$data
##                                                                                          lower_dir
##   "/var/lib/docker/overlay2/e1a21604d525ede2c5e9e6d59ac7dceb33bc7469ad98cc9997477a38c310305c/diff"
##                                                                                         merged_dir
## "/var/lib/docker/overlay2/934d66f90f6c661634b1618ea61d7f0b87149631cb4715059b862e18c27eac1f/merged"
##                                                                                          upper_dir
##   "/var/lib/docker/overlay2/934d66f90f6c661634b1618ea61d7f0b87149631cb4715059b862e18c27eac1f/diff"
##                                                                                           work_dir
##   "/var/lib/docker/overlay2/934d66f90f6c661634b1618ea61d7f0b87149631cb4715059b862e18c27eac1f/work"
##
##
## $root_fs
## $root_fs$type
## [1] "layers"
##
## $root_fs$layers
## [1] "sha256:6b27de954cca6332272e7709b7d8ceccee1489d9452af73391df360a26123580"
## [2] "sha256:14794d0f3100e41f9a96e1d181db26e010ae56489b484f0abcc782dcfc438de5"
##
## $root_fs$base_layer
## [1] NA
##
##
## $metadata
## $metadata$last_tag_time
## [1] "2020-01-12T10:05:44.5147212Z"</code></pre>
<p>the exact format varies between docker API versions but should be the same for all images within an API version.</p>
<p>The <code><a href="https://rdrr.io/r/utils/savehistory.html">history()</a></code> method returns a data.frame of information about the history of an image (i.e., the layers that it is constructed from)</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">history</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##                                                                        id
## 1 sha256:244154bfbb9995fc3c5fede726ec4c2679ba393375f2a8130ffd8537dcce3285
## 2 sha256:346745e9ebc8af6b623cdf5729ceddfd215e33d7886a7e72e71beba46d9bceca
## 3 sha256:d5b6a0eaa685450861afb86bc00f05762bba84284ad2b36b252893f4c0972bb4
## 4 sha256:bfead14674a0cf29a4cb48ee5b11d006b7451ddd098086bc3866ded70821cd8d
## 5 sha256:cc0abc535e36a7ede71978ba2bbd8159b8a5420b91f2fbc520cdf5f673640a34
## 6                                                               &lt;missing&gt;
##      created
## 1 1578823544
## 2 1578823544
## 3 1578823543
## 4 1578823543
## 5 1577215212
## 6 1577215212
##                                                                                                                created_by
## 1                                                                /bin/sh -c #(nop)  ENTRYPOINT ["/usr/local/bin/iterate"]
## 2                                                                        /bin/sh -c #(nop)  LABEL stevedore_version=0.0.1
## 3                                               /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "chmod +x /usr/local/bin/iterate"]
## 4 /bin/sh -c #(nop) COPY file:8b8ba7864a94787016cc3c519efd97a1c7dde8a1b64fec3d078096872b2ece4c in /usr/local/bin/iterate
## 5                                                                                      /bin/sh -c #(nop)  CMD ["/bin/sh"]
## 6                       /bin/sh -c #(nop) ADD file:36fdc8cb08228a87093fb227736f4ce1d4d6c15366326dea541fbbd863976ee5 in /
##           tags    size comment
## 1 richfitz....       0
## 2                    0
## 3                    0
## 4                  306
## 5 alpine:l....       0
## 6              5591300</code></pre>
<p>(printing these objects is a real challenge!).</p>
<p>The <code>export()</code> method exports an image as a tar object. There is some work still required to make this work nicely (currently it returns a [potentially long] raw vector).</p>
<p>There are several methods that operate to modify or destroy the image:</p>
<p>The <code>$tag()</code> method will tag an image, for example</p>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">tag</span><span class="op">(</span><span class="st">"richfitz/iterate"</span>, <span class="st">"0.0.1"</span><span class="op">)</span>
<span class="va">img</span><span class="op">$</span><span class="fu">reload</span><span class="op">(</span><span class="op">)</span>
<span class="va">img</span><span class="op">$</span><span class="fu">tags</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "richfitz/iterate:0.0.1"  "richfitz/iterate:latest"</code></pre>
<p>While the <code>$untag()</code> method will remove a tag</p>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">untag</span><span class="op">(</span><span class="st">"richfitz/iterate:0.0.1"</span><span class="op">)</span></code></pre></div>
<p>The <code>$remove()</code> method will remove an image - this returns a data.frame indicating what actually happened (images are only actually deleted if there are no other tags pointing at an image <em>and</em> if <code>noprune</code> is not <code>TRUE</code>.</p>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">img</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##                  untagged
## 1 richfitz/iterate:latest
## 2                    &lt;NA&gt;
## 3                    &lt;NA&gt;
## 4                    &lt;NA&gt;
## 5                    &lt;NA&gt;
## 6                    &lt;NA&gt;
##                                                                   deleted
## 1                                                                    &lt;NA&gt;
## 2 sha256:244154bfbb9995fc3c5fede726ec4c2679ba393375f2a8130ffd8537dcce3285
## 3 sha256:346745e9ebc8af6b623cdf5729ceddfd215e33d7886a7e72e71beba46d9bceca
## 4 sha256:d5b6a0eaa685450861afb86bc00f05762bba84284ad2b36b252893f4c0972bb4
## 5 sha256:bfead14674a0cf29a4cb48ee5b11d006b7451ddd098086bc3866ded70821cd8d
## 6 sha256:ce1557b8602d2427fb71296d2c6ab9b05103d830cdf2eb5d45cdfe25c3ed11dd</code></pre>
</div>
</div>
<div id="volumes" class="section level2">
<h2 class="hasAnchor">
<a href="#volumes" class="anchor"></a>Volumes</h2>
<p>Docker volumes provide a useful abstraction for interacting with (possibly persistent) file volumes across containers. To create a volume using <code>stevedore</code> (equivalent to <code>docker volume create</code>) use <code>$volume$create()</code>:</p>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">volume</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"myvolume"</span><span class="op">)</span></code></pre></div>
<p>Volumes can be listed:</p>
<div class="sourceCode" id="cb148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">volume</span><span class="op">$</span><span class="fu">list</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##                                                               name driver
## 1                                                         myvolume  local
## 2 dc5d8f843c0fefd3e0c6a729e7326fe262c94aa50a49065448d7ef664c53a285  local
##                                                                                       mountpoint
## 1                                                         /var/lib/docker/volumes/myvolume/_data
## 2 /var/lib/docker/volumes/dc5d8f843c0fefd3e0c6a729e7326fe262c94aa50a49065448d7ef664c53a285/_data
##             created_at status labels scope options usage_data
## 1 2020-01-12T10:05:47Z               local             NA, NA
## 2 2019-12-23T08:27:51Z               local             NA, NA</code></pre>
<div id="working-with-volume-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-volume-objects" class="anchor"></a>Working with volume objects</h3>
<p>There’s very little that can be done with volume objects:</p>
<div class="sourceCode" id="cb150"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span></code></pre></div>
<pre><code>## &lt;docker_volume&gt;
##   help(help_type = getOption("help_type"))
##   inspect(reload = TRUE)
##   map(path, readonly = FALSE)
##   name()
##   reload()
##   remove(force = NULL)</code></pre>
<p>We can get the name:</p>
<div class="sourceCode" id="cb152"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span><span class="op">$</span><span class="fu">name</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "myvolume"</code></pre>
<p>Inspect the metadata</p>
<div class="sourceCode" id="cb154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span><span class="op">$</span><span class="fu">inspect</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $name
## [1] "myvolume"
##
## $driver
## [1] "local"
##
## $mountpoint
## [1] "/var/lib/docker/volumes/myvolume/_data"
##
## $created_at
## [1] "2020-01-12T10:05:47Z"
##
## $status
## NULL
##
## $labels
## NULL
##
## $scope
## [1] "local"
##
## $options
## NULL
##
## $usage_data
## NULL</code></pre>
<p>Generate mount definitions:</p>
<div class="sourceCode" id="cb156"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span><span class="op">$</span><span class="fu">map</span><span class="op">(</span><span class="st">"/comtainer/path"</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "myvolume:/comtainer/path"</code></pre>
<p>and can remove the volume</p>
<div class="sourceCode" id="cb158"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>everything else comes from using volumes with containers.</p>
<p>Containers are mounted the same way as from the docker command line - with a string in the form <code>&lt;host&gt;:&lt;container&gt;</code>. Here we can use the volume name on the host side, so saying <code>&lt;myvolume&gt;:/myvolume</code> mounts our volume at <code>/myvolume</code> within the container. This can be done easily with the <code>$map()</code> method.</p>
<div class="sourceCode" id="cb160"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">vol</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">volume</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"myvolume"</span><span class="op">)</span>
<span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span>
  <span class="st">"alpine:latest"</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sh"</span>, <span class="st">"-c"</span>, <span class="st">"echo hello world &gt; /myvolume/output"</span><span class="op">)</span>,
  volumes <span class="op">=</span> <span class="va">vol</span><span class="op">$</span><span class="fu">map</span><span class="op">(</span><span class="st">"/myvolume"</span><span class="op">)</span>,
  rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## &lt;docker_run_output&gt;
##   $container:
##     &lt;docker_container&gt;
##       id: 946dbe3f449dd8433847f1517af6106385ff1d31ed755f671ee10a732e31ac65
##       name: determined_easley
##
##   $logs:
##</code></pre>
<p>(We use <code>sh -c</code> here so that the redirect operates within the container - the third argument is evaluated by the shell within the container and redirects the value that is echoed to a file.)</p>
<p>We can see the result of this by using a second container to read the file:</p>
<div class="sourceCode" id="cb162"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span>
  <span class="st">"alpine:latest"</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"cat"</span>, <span class="st">"/myvolume/output"</span><span class="op">)</span>,
  volumes <span class="op">=</span> <span class="va">vol</span><span class="op">$</span><span class="fu">map</span><span class="op">(</span><span class="st">"/myvolume"</span><span class="op">)</span>,
  rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">$</span><span class="va">logs</span></code></pre></div>
<pre><code>## O&gt; hello world</code></pre>
<pre><code>## O&gt; hello world</code></pre>
</div>
</div>
<div id="networks" class="section level2">
<h2 class="hasAnchor">
<a href="#networks" class="anchor"></a>Networks</h2>
<p>Docker “networks” make it easy to get containers communicating with each other without exposing ports to the host. To achive this, one creates a docker network, then create containers attached to that network (containers can also be attached to networks after creation).</p>
<div class="sourceCode" id="cb165"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">network</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"mynetwork"</span><span class="op">)</span></code></pre></div>
<p>Networks can be listed:</p>
<div class="sourceCode" id="cb166"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">network</span><span class="op">$</span><span class="fu">list</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##        name
## 1      host
## 2 mynetwork
## 3      none
## 4    bridge
##                                                                 id
## 1 d5a076bd27b8f3a0963da06b5c149e6e7ab63ebe5649e124fdf8a22602b215c2
## 2 05492a54216e3b100caa82959b714897dd10dd0292ae82f730328c2d6d29b1bb
## 3 80bf98ad0e7fac320903a891936aa9680462769b37168e38b483c7ff9612bb2c
## 4 8b98e06edb0adb42f306a3d86d2f4f3d62b7a9d15279d7c44d37908c120df1ac
##                          created scope driver enable_ipv6         ipam
## 1 2019-03-09T11:06:26.652857909Z local   host       FALSE default,....
## 2   2020-01-12T10:05:50.1991445Z local bridge       FALSE default,....
## 3 2019-03-09T11:06:26.606552055Z local   null       FALSE default,....
## 4 2020-01-10T06:57:36.297181373Z local bridge       FALSE default,....
##   internal attachable ingress containers      options labels
## 1    FALSE      FALSE   FALSE
## 2    FALSE      FALSE   FALSE
## 3    FALSE      FALSE   FALSE
## 4    FALSE      FALSE   FALSE            true, tr....</code></pre>
<p>The networks <code>bridge</code>, <code>host</code> and <code>none</code> always exist - they are special to docker.</p>
<div id="working-with-network-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-network-objects" class="anchor"></a>Working with network objects</h3>
<p>Like volume objects, network objects do very little themselves:</p>
<div class="sourceCode" id="cb168"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span></code></pre></div>
<pre><code>## &lt;docker_network&gt;
##   connect(container = NULL, endpoint_config = NULL)
##   containers(reload = TRUE)
##   disconnect(container = NULL, force = NULL)
##   help(help_type = getOption("help_type"))
##   id()
##   inspect(reload = TRUE)
##   name(reload = TRUE)
##   reload()
##   remove()</code></pre>
<p>The <code>$name()</code> and <code>$id()</code> methods get the name and id of the network</p>
<div class="sourceCode" id="cb170"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">name</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "mynetwork"</code></pre>
<div class="sourceCode" id="cb172"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">id</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "05492a54216e3b100caa82959b714897dd10dd0292ae82f730328c2d6d29b1bb"</code></pre>
<p><code>$inspect()</code> gets detailed metadata</p>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">inspect</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $name
## [1] "mynetwork"
##
## $id
## [1] "05492a54216e3b100caa82959b714897dd10dd0292ae82f730328c2d6d29b1bb"
##
## $created
## [1] "2020-01-12T10:05:50.1991445Z"
##
## $scope
## [1] "local"
##
## $driver
## [1] "bridge"
##
## $enable_ipv6
## [1] FALSE
##
## $ipam
## $ipam$driver
## [1] "default"
##
## $ipam$config
## $ipam$config[[1]]
##          subnet         gateway
## "172.18.0.0/16"    "172.18.0.1"
##
##
## $ipam$options
## list()
##
##
## $internal
## [1] FALSE
##
## $attachable
## [1] FALSE
##
## $ingress
## [1] FALSE
##
## $containers
## list()
##
## $options
## character(0)
##
## $labels
## character(0)</code></pre>
<p><code>$containers()</code> lists containers attached to the network (currently an empty list - this network has no attached containers)</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">containers</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## list()</code></pre>
<p><code>$remove()</code> removes the network</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Generally you’ll want to put containers onto a network.</p>
<p>The setup here is to create a network, and then use the <code>network</code> argument to <code>$container$run()</code> to attach a container to that network. Once established, containers on the same network can use another docker container’s name as the hostname and communicate!</p>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">network</span><span class="op">$</span><span class="fu">create</span><span class="op">(</span><span class="st">"mynetwork"</span><span class="op">)</span>
<span class="va">server</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"nginx"</span>, network <span class="op">=</span> <span class="va">nw</span>, name <span class="op">=</span> <span class="st">"server"</span>,
                               detach <span class="op">=</span> <span class="cn">TRUE</span>, rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">server</span><span class="op">$</span><span class="fu">status</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Now we can attach other networks to this container and communicate with the server:</p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"alpine:latest"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ping"</span>, <span class="st">"server"</span>, <span class="st">"-c"</span>, <span class="st">"3"</span><span class="op">)</span>,
                     network <span class="op">=</span> <span class="va">nw</span>, stream <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/showConnections.html">stdout</a></span><span class="op">(</span><span class="op">)</span>, rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; PING server (172.19.0.2): 56 data bytes
## O&gt; 64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.099 ms
## O&gt; 64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.208 ms
## O&gt; 64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.228 ms
## O&gt;
## O&gt; --- server ping statistics ---
## O&gt; 3 packets transmitted, 3 packets received, 0% packet loss
## O&gt; round-trip min/avg/max = 0.099/0.178/0.228 ms</code></pre>
<pre><code>## &lt;docker_run_output&gt;
##   $container:
##     &lt;docker_container&gt;
##       id: 36ee5c4501190e86eac95a52284cbfd69a22fe74d95088773f41627e3dc57c93
##       name: agitated_pasteur
##
##   $logs:
##     O&gt; PING server (172.19.0.2): 56 data bytes
##     O&gt; 64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.099 ms
##     O&gt; 64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.208 ms
##     O&gt; 64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.228 ms
##     O&gt;
##     O&gt; --- server ping statistics ---
##     O&gt; 3 packets transmitted, 3 packets received, 0% packet loss
##     O&gt; round-trip min/avg/max = 0.099/0.178/0.228 ms</code></pre>
<p>Omitting the <code>network</code> argument, the second container can’t find the server:</p>
<div class="sourceCode" id="cb185"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"alpine:latest"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ping"</span>, <span class="st">"server"</span>, <span class="st">"-c"</span>, <span class="st">"3"</span><span class="op">)</span>,
                     stream <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/showConnections.html">stdout</a></span><span class="op">(</span><span class="op">)</span>, rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## E&gt; ping: bad address 'server'</code></pre>
<pre><code>## Error: Command 'ping server -c 3' in image 'alpine:latest' returned non-zero exit status 1
## ping: bad address 'server'</code></pre>
<p>The server container exposes a webserver on port 80. For containers on the network we can access this port:</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res</span> <span class="op">&lt;-</span> <span class="va">docker</span><span class="op">$</span><span class="va">container</span><span class="op">$</span><span class="fu">run</span><span class="op">(</span><span class="st">"richfitz/curl"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"curl"</span>, <span class="st">"-s"</span>, <span class="st">"http://server"</span><span class="op">)</span>,
                            network <span class="op">=</span> <span class="va">nw</span>, rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## O&gt; &lt;!DOCTYPE html&gt;
## O&gt; &lt;html&gt;
## O&gt; &lt;head&gt;
## O&gt; &lt;title&gt;Welcome to nginx!&lt;/title&gt;
## O&gt; &lt;style&gt;
## O&gt;     body {
## O&gt;         width: 35em;
## O&gt;         margin: 0 auto;
## O&gt;         font-family: Tahoma, Verdana, Arial, sans-serif;
## O&gt;     }
## O&gt; &lt;/style&gt;
## O&gt; &lt;/head&gt;
## O&gt; &lt;body&gt;
## O&gt; &lt;h1&gt;Welcome to nginx!&lt;/h1&gt;
## O&gt; &lt;p&gt;If you see this page, the nginx web server is successfully installed and
## O&gt; working. Further configuration is required.&lt;/p&gt;
## O&gt;
## O&gt; &lt;p&gt;For online documentation and support please refer to
## O&gt; &lt;a href="http://nginx.org/"&gt;nginx.org&lt;/a&gt;.&lt;br/&gt;
## O&gt; Commercial support is available at
## O&gt; &lt;a href="http://nginx.com/"&gt;nginx.com&lt;/a&gt;.&lt;/p&gt;
## O&gt;
## O&gt; &lt;p&gt;&lt;em&gt;Thank you for using nginx.&lt;/em&gt;&lt;/p&gt;
## O&gt; &lt;/body&gt;
## O&gt; &lt;/html&gt;</code></pre>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">res</span><span class="op">$</span><span class="va">logs</span>, <span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "&lt;!DOCTYPE html&gt;\n"
##  [2] "&lt;html&gt;\n"
##  [3] "&lt;head&gt;\n"
##  [4] "&lt;title&gt;Welcome to nginx!&lt;/title&gt;\n"
##  [5] "&lt;style&gt;\n"
##  [6] "    body {\n"
##  [7] "        width: 35em;\n"
##  [8] "        margin: 0 auto;\n"
##  [9] "        font-family: Tahoma, Verdana, Arial, sans-serif;\n"
## [10] "    }\n"</code></pre>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">server</span><span class="op">$</span><span class="kw">stop</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nw</span><span class="op">$</span><span class="fu">remove</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## NULL</code></pre>
</div>
</div>
<div id="other-docker-functions" class="section level2">
<h2 class="hasAnchor">
<a href="#other-docker-functions" class="anchor"></a>Other docker functions</h2>
<p>There are a few functions at the top level of the <code>docker_client</code> object:</p>
<p><code>$ping()</code> tests the connection to the server and reports the API version for the server - this is a (for docker) very fast function to use to test that things seem to be working.</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="fu">ping</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "OK"
## attr(,"api_version")
## [1] "1.39"
## attr(,"buildkit_version")
## [1] NA
## attr(,"docker_experimental")
## [1] FALSE</code></pre>
<p><code>$api_version()</code> reports the API version that the <em>client</em> is using (this can be varied from 1.25 to 1.39)</p>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="fu">api_version</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "1.39"</code></pre>
<p><code>$version()</code> reports detailed version information from the server:</p>
<div class="sourceCode" id="cb200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="fu">version</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $platform
## $platform$name
## [1] "Docker Engine - Community"
##
##
## $components
##     name version      details
## 1 Engine 18.09.2 1.39, am....
##
## $version
## [1] "18.09.2"
##
## $api_version
## [1] "1.39"
##
## $min_api_version
## [1] "1.12"
##
## $git_commit
## [1] "6247962"
##
## $go_version
## [1] "go1.10.6"
##
## $os
## [1] "linux"
##
## $arch
## [1] "amd64"
##
## $kernel_version
## [1] "4.9.125-linuxkit"
##
## $experimental
## [1] NA
##
## $build_time
## [1] "2019-02-10T04:13:06.000000000+00:00"</code></pre>
<p><code>$info()</code> reports a bunch of other information about the state of the server (Docker describes this as “get system information” in its documentation) - this is equivalent to running <code>docker info</code></p>
<div class="sourceCode" id="cb202"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">docker</span><span class="op">$</span><span class="fu">info</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## $id
## [1] "54B2:VUDF:CFVG:KTXY:5ZI6:S7NK:LQNM:7CFA:X6TH:5PRV:SUFC:ZDK4"
##
## $containers
## [1] 0
##
## $containers_running
## [1] 0
##
## $containers_paused
## [1] 0
##
## $containers_stopped
## [1] 0
##
## $images
## [1] 73
##
## $driver
## [1] "overlay2"
##
## $driver_status
## $driver_status[[1]]
## [1] "Backing Filesystem" "extfs"
##
## $driver_status[[2]]
## [1] "Supports d_type" "true"
##
## $driver_status[[3]]
## [1] "Native Overlay Diff" "true"
##
##
## $docker_root_dir
## [1] "/var/lib/docker"
##
## $system_status
## list()
##
## $plugins
## $plugins$volume
## [1] "local"
##
## $plugins$network
## [1] "bridge"  "host"    "macvlan" "null"    "overlay"
##
## $plugins$authorization
## character(0)
##
## $plugins$log
##  [1] "awslogs"    "fluentd"    "gcplogs"    "gelf"       "journald"
##  [6] "json-file"  "local"      "logentries" "splunk"     "syslog"
##
##
## $memory_limit
## [1] TRUE
##
## $swap_limit
## [1] TRUE
##
## $kernel_memory
## [1] TRUE
##
## $cpu_cfs_period
## [1] TRUE
##
## $cpu_cfs_quota
## [1] TRUE
##
## $cpu_shares
## [1] TRUE
##
## $cpu_set
## [1] TRUE
##
## $oom_kill_disable
## [1] TRUE
##
## $ipv4_forwarding
## [1] TRUE
##
## $bridge_nf_iptables
## [1] TRUE
##
## $bridge_nf_ip6tables
## [1] TRUE
##
## $debug
## [1] TRUE
##
## $n_fd
## [1] 26
##
## $n_goroutines
## [1] 53
##
## $system_time
## [1] "2020-01-12T10:06:01.1253405Z"
##
## $logging_driver
## [1] "json-file"
##
## $cgroup_driver
## [1] "cgroupfs"
##
## $n_events_listener
## [1] 2
##
## $kernel_version
## [1] "4.9.125-linuxkit"
##
## $operating_system
## [1] "Docker for Mac"
##
## $os_type
## [1] "linux"
##
## $architecture
## [1] "x86_64"
##
## $n_cpu
## [1] 2
##
## $mem_total
## [1] 2096164864
##
## $index_server_address
## [1] "https://index.docker.io/v1/"
##
## $registry_config
## $registry_config$allow_nondistributable_artifacts_cidrs
## character(0)
##
## $registry_config$allow_nondistributable_artifacts_hostnames
## character(0)
##
## $registry_config$insecure_registry_cidrs
## [1] "127.0.0.0/8"
##
## $registry_config$index_configs
## $registry_config$index_configs$docker.io
## $registry_config$index_configs$docker.io$name
## [1] "docker.io"
##
## $registry_config$index_configs$docker.io$mirrors
## character(0)
##
## $registry_config$index_configs$docker.io$secure
## [1] TRUE
##
## $registry_config$index_configs$docker.io$official
## [1] TRUE
##
##
##
## $registry_config$mirrors
## character(0)
##
##
## $generic_resources
## [1] named_resource_spec    discrete_resource_spec
## &lt;0 rows&gt; (or 0-length row.names)
##
## $http_proxy
## [1] "gateway.docker.internal:3128"
##
## $https_proxy
## [1] "gateway.docker.internal:3129"
##
## $no_proxy
## [1] ""
##
## $name
## [1] "linuxkit-025000000001"
##
## $labels
## character(0)
##
## $experimental_build
## [1] FALSE
##
## $server_version
## [1] "18.09.2"
##
## $cluster_store
## [1] ""
##
## $cluster_advertise
## [1] ""
##
## $runtimes
## $runtimes$runc
## $runtimes$runc$path
## [1] "runc"
##
## $runtimes$runc$runtime_args
## character(0)
##
##
##
## $default_runtime
## [1] "runc"
##
## $swarm
## $swarm$node_id
## [1] ""
##
## $swarm$node_addr
## [1] ""
##
## $swarm$local_node_state
## [1] "inactive"
##
## $swarm$control_available
## [1] FALSE
##
## $swarm$error
## [1] ""
##
## $swarm$remote_managers
## [1] node_id addr
## &lt;0 rows&gt; (or 0-length row.names)
##
## $swarm$nodes
## [1] NA
##
## $swarm$managers
## [1] NA
##
## $swarm$cluster
## NULL
##
##
## $live_restore_enabled
## [1] FALSE
##
## $isolation
## [1] ""
##
## $init_binary
## [1] "docker-init"
##
## $containerd_commit
## $containerd_commit$id
## [1] "9754871865f7fe2f4e74d43e2fc7ccd237edcbce"
##
## $containerd_commit$expected
## [1] "9754871865f7fe2f4e74d43e2fc7ccd237edcbce"
##
##
## $runc_commit
## $runc_commit$id
## [1] "09c8266bf2fcf9519a651b04ae54c967b9ab86ec"
##
## $runc_commit$expected
## [1] "09c8266bf2fcf9519a651b04ae54c967b9ab86ec"
##
##
## $init_commit
## $init_commit$id
## [1] "fec3683"
##
## $init_commit$expected
## [1] "fec3683"
##
##
## $security_options
## [1] "name=seccomp,profile=default"
##
## $product_license
## [1] "Community Engine"
##
## $warnings
## character(0)</code></pre>
<p>Finally, <code>$df()</code> will return information about resource and data usage by docker - all containers, networks, volumes, etc.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Rich FitzJohn.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
